SimileAjax.DateTime={};SimileAjax.DateTime.MILLISECOND=0;SimileAjax.DateTime.SECOND=1;SimileAjax.DateTime.MINUTE=2;SimileAjax.DateTime.HOUR=3;SimileAjax.DateTime.DAY=4;SimileAjax.DateTime.WEEK=5;SimileAjax.DateTime.MONTH=6;SimileAjax.DateTime.YEAR=7;SimileAjax.DateTime.DECADE=8;SimileAjax.DateTime.CENTURY=9;SimileAjax.DateTime.MILLENNIUM=10;SimileAjax.DateTime.EPOCH=-1;SimileAjax.DateTime.ERA=-2;SimileAjax.DateTime.gregorianUnitLengths=[];
(function(){var a=SimileAjax.DateTime,b=a.gregorianUnitLengths;b[a.MILLISECOND]=1;b[a.SECOND]=1E3;b[a.MINUTE]=b[a.SECOND]*60;b[a.HOUR]=b[a.MINUTE]*60;b[a.DAY]=b[a.HOUR]*24;b[a.WEEK]=b[a.DAY]*7;b[a.MONTH]=b[a.DAY]*31;b[a.YEAR]=b[a.DAY]*365;b[a.DECADE]=b[a.YEAR]*10;b[a.CENTURY]=b[a.YEAR]*100;b[a.MILLENNIUM]=b[a.YEAR]*1E3})();SimileAjax.DateTime._dateRegexp=/^(-?)([0-9]{4})((-?([0-9]{2})(-?([0-9]{2}))?)|(-?([0-9]{3}))|(-?W([0-9]{2})(-?([1-7]))?))?$/;SimileAjax.DateTime._timezoneRegexp=/Z|(([-+])([0-9]{2})(:?([0-9]{2}))?)$/;
SimileAjax.DateTime._timeRegexp=/^([0-9]{2})(:?([0-9]{2})(:?([0-9]{2})(.([0-9]+))?)?)?$/;
SimileAjax.DateTime.setIso8601Date=function(a,b){var d=b.match(SimileAjax.DateTime._dateRegexp);if(!d)throw Error("Invalid date string: "+b);var c=d[5],f=d[7],e=d[9],g=d[11],h=d[13]?d[13]:1;a.setUTCFullYear((d[1]=="-"?-1:1)*d[2]);e?(a.setUTCMonth(0),a.setUTCDate(Number(e))):g?(a.setUTCMonth(0),a.setUTCDate(1),d=(d=a.getUTCDay())?d:7,g=Number(h)+7*Number(g),d<=4?a.setUTCDate(g+1-d):a.setUTCDate(g+8-d)):(c&&(a.setUTCDate(1),a.setUTCMonth(c-1)),f&&a.setUTCDate(f));return a};
SimileAjax.DateTime.setIso8601Time=function(a,b){var d=b.match(SimileAjax.DateTime._timeRegexp);if(!d)return SimileAjax.Debug.warn("Invalid time string: "+b),!1;var c=Number(d[3]?d[3]:0),f=d[5]?d[5]:0,e=d[7]?Number("0."+d[7])*1E3:0;a.setUTCHours(d[1]);a.setUTCMinutes(c);a.setUTCSeconds(f);a.setUTCMilliseconds(e);return a};SimileAjax.DateTime.timezoneOffset=(new Date).getTimezoneOffset();
SimileAjax.DateTime.setIso8601=function(a,b){var d=null,c=b.indexOf("T")==-1?b.split(" "):b.split("T");SimileAjax.DateTime.setIso8601Date(a,c[0]);if(c.length==2){var f=c[1].match(SimileAjax.DateTime._timezoneRegexp);f&&(f[0]=="Z"?d=0:(d=Number(f[3])*60+Number(f[5]),d*=f[2]=="-"?1:-1),c[1]=c[1].substr(0,c[1].length-f[0].length));SimileAjax.DateTime.setIso8601Time(a,c[1])}d==null&&(d=a.getTimezoneOffset());a.setTime(a.getTime()+d*6E4);return a};
SimileAjax.DateTime.parseIso8601DateTime=function(a){try{return SimileAjax.DateTime.setIso8601(new Date(0),a)}catch(b){return null}};SimileAjax.DateTime.parseGregorianDateTime=function(a){if(a==null)return null;else if(a instanceof Date)return a;var b=a.toString();if(b.length>0&&b.length<8){var d=b.indexOf(" ");d>0?(a=parseInt(b.substr(0,d)),b.substr(d+1).toLowerCase()=="bc"&&(a=1-a)):a=parseInt(b);b=new Date(0);b.setUTCFullYear(a);return b}try{return new Date(Date.parse(b))}catch(c){return null}};
SimileAjax.DateTime.roundDownToInterval=function(a,b,d,c,f){d*=SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.HOUR];var e=new Date(a.getTime()+d),g=function(a){a.setUTCMilliseconds(0);a.setUTCSeconds(0);a.setUTCMinutes(0);a.setUTCHours(0)},h=function(a){g(a);a.setUTCDate(1);a.setUTCMonth(0)};switch(b){case SimileAjax.DateTime.MILLISECOND:b=e.getUTCMilliseconds();e.setUTCMilliseconds(b-b%c);break;case SimileAjax.DateTime.SECOND:e.setUTCMilliseconds(0);b=e.getUTCSeconds();e.setUTCSeconds(b-
b%c);break;case SimileAjax.DateTime.MINUTE:e.setUTCMilliseconds(0);e.setUTCSeconds(0);b=e.getUTCMinutes();e.setTime(e.getTime()-b%c*SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.MINUTE]);break;case SimileAjax.DateTime.HOUR:e.setUTCMilliseconds(0);e.setUTCSeconds(0);e.setUTCMinutes(0);b=e.getUTCHours();e.setUTCHours(b-b%c);break;case SimileAjax.DateTime.DAY:g(e);break;case SimileAjax.DateTime.WEEK:g(e);c=(e.getUTCDay()+7-f)%7;e.setTime(e.getTime()-c*SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.DAY]);
break;case SimileAjax.DateTime.MONTH:g(e);e.setUTCDate(1);b=e.getUTCMonth();e.setUTCMonth(b-b%c);break;case SimileAjax.DateTime.YEAR:h(e);b=e.getUTCFullYear();e.setUTCFullYear(b-b%c);break;case SimileAjax.DateTime.DECADE:h(e);e.setUTCFullYear(Math.floor(e.getUTCFullYear()/10)*10);break;case SimileAjax.DateTime.CENTURY:h(e);e.setUTCFullYear(Math.floor(e.getUTCFullYear()/100)*100);break;case SimileAjax.DateTime.MILLENNIUM:h(e),e.setUTCFullYear(Math.floor(e.getUTCFullYear()/1E3)*1E3)}a.setTime(e.getTime()-
d)};SimileAjax.DateTime.roundUpToInterval=function(a,b,d,c,f){var e=a.getTime();SimileAjax.DateTime.roundDownToInterval(a,b,d,c,f);a.getTime()<e&&a.setTime(a.getTime()+SimileAjax.DateTime.gregorianUnitLengths[b]*c)};
SimileAjax.DateTime.incrementByInterval=function(a,b,d){var d=(typeof d=="undefined"?0:d)*SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.HOUR],c=new Date(a.getTime()+d);switch(b){case SimileAjax.DateTime.MILLISECOND:c.setTime(c.getTime()+1);break;case SimileAjax.DateTime.SECOND:c.setTime(c.getTime()+1E3);break;case SimileAjax.DateTime.MINUTE:c.setTime(c.getTime()+SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.MINUTE]);break;case SimileAjax.DateTime.HOUR:c.setTime(c.getTime()+
SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.HOUR]);break;case SimileAjax.DateTime.DAY:c.setUTCDate(c.getUTCDate()+1);break;case SimileAjax.DateTime.WEEK:c.setUTCDate(c.getUTCDate()+7);break;case SimileAjax.DateTime.MONTH:c.setUTCMonth(c.getUTCMonth()+1);break;case SimileAjax.DateTime.YEAR:c.setUTCFullYear(c.getUTCFullYear()+1);break;case SimileAjax.DateTime.DECADE:c.setUTCFullYear(c.getUTCFullYear()+10);break;case SimileAjax.DateTime.CENTURY:c.setUTCFullYear(c.getUTCFullYear()+100);
break;case SimileAjax.DateTime.MILLENNIUM:c.setUTCFullYear(c.getUTCFullYear()+1E3)}a.setTime(c.getTime()-d)};SimileAjax.DateTime.removeTimeZoneOffset=function(a,b){return new Date(a.getTime()+b*SimileAjax.DateTime.gregorianUnitLengths[SimileAjax.DateTime.HOUR])};SimileAjax.DateTime.getTimezone=function(){return(new Date).getTimezoneOffset()/-60};
