SimileAjax.Graphics={};SimileAjax.Graphics.pngIsTranslucent=!SimileAjax.Platform.browser.isIE||SimileAjax.Platform.browser.majorVersion>6;SimileAjax.Graphics.pngIsTranslucent||SimileAjax.includeCssFile(document,SimileAjax.urlPrefix+"styles/graphics-ie6.css");SimileAjax.Graphics._createTranslucentImage1=function(a,b){var c=document.createElement("img");c.setAttribute("src",a);if(b!=null)c.style.verticalAlign=b;return c};
SimileAjax.Graphics._createTranslucentImage2=function(a,b){var c=document.createElement("img");c.style.width="1px";c.style.height="1px";c.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a+"', sizingMethod='image')";c.style.verticalAlign=b!=null?b:"middle";return c};SimileAjax.Graphics.createTranslucentImage=SimileAjax.Graphics.pngIsTranslucent?SimileAjax.Graphics._createTranslucentImage1:SimileAjax.Graphics._createTranslucentImage2;
SimileAjax.Graphics._createTranslucentImageHTML1=function(a,b){return'<img src="'+a+'"'+(b!=null?' style="vertical-align: '+b+';"':"")+" />"};SimileAjax.Graphics._createTranslucentImageHTML2=function(a,b){return"<img src='"+a+"' style=\""+("width: 1px; height: 1px; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a+"', sizingMethod='image');"+(b!=null?" vertical-align: "+b+";":""))+'" />'};
SimileAjax.Graphics.createTranslucentImageHTML=SimileAjax.Graphics.pngIsTranslucent?SimileAjax.Graphics._createTranslucentImageHTML1:SimileAjax.Graphics._createTranslucentImageHTML2;SimileAjax.Graphics.setOpacity=function(a,b){if(SimileAjax.Platform.browser.isIE)a.style.filter="progid:DXImageTransform.Microsoft.Alpha(Style=0,Opacity="+b+")";else{var c=(b/100).toString();a.style.opacity=c;a.style.MozOpacity=c}};
SimileAjax.Graphics.bubbleConfig={containerCSSClass:"simileAjax-bubble-container",innerContainerCSSClass:"simileAjax-bubble-innerContainer",contentContainerCSSClass:"simileAjax-bubble-contentContainer",borderGraphicSize:50,borderGraphicCSSClassPrefix:"simileAjax-bubble-border-",arrowGraphicTargetOffset:33,arrowGraphicLength:100,arrowGraphicWidth:49,arrowGraphicCSSClassPrefix:"simileAjax-bubble-arrow-",closeGraphicCSSClass:"simileAjax-bubble-close",extraPadding:20};
SimileAjax.Graphics.createBubbleForContentAndPoint=function(a,b,c,e,f,d){typeof e!="number"&&(e=300);typeof d!="number"&&(d=0);a.style.position="absolute";a.style.left="-5000px";a.style.top="0px";a.style.width=e+"px";document.body.appendChild(a);window.setTimeout(function(){var e=a.scrollWidth+10,j=a.scrollHeight+10,i=0;d>0&&j>d&&(j=d,i=e-25);j=SimileAjax.Graphics.createBubbleForPoint(b,c,e,j,f);document.body.removeChild(a);a.style.position="static";a.style.left="";a.style.top="";i>0?(e=document.createElement("div"),
a.style.width="",e.style.width=i+"px",e.appendChild(a),j.content.appendChild(e)):(a.style.width=e+"px",j.content.appendChild(a))},200)};
SimileAjax.Graphics.createBubbleForPoint=function(a,b,c,e,f){var c=parseInt(c,10),e=parseInt(e,10),d=SimileAjax.Graphics.bubbleConfig,m=SimileAjax.Graphics.pngIsTranslucent?"pngTranslucent":"pngNotTranslucent",j=function(a){return a+" "+a+"-"+m},i=document.createElement("div");i.className=j(d.containerCSSClass);i.style.width=c+"px";i.style.height=e+"px";var n=document.createElement("div");n.className=j(d.innerContainerCSSClass);i.appendChild(n);var h={_closed:!1},o=SimileAjax.WindowManager.pushLayer(function(){if(!h._closed)document.body.removeChild(h._div),
h._doc=null,h._div=null,h._content=null,h._closed=!0},!0,i);h._div=i;h.close=function(){SimileAjax.WindowManager.popLayer(o)};var g=function(a){var b=document.createElement("div");b.className=j(d.borderGraphicCSSClassPrefix+a);n.appendChild(b)};g("top-left");g("top-right");g("bottom-left");g("bottom-right");g("left");g("right");g("top");g("bottom");g=document.createElement("div");g.className=j(d.contentContainerCSSClass);n.appendChild(g);h.content=g;g=document.createElement("div");g.className=j(d.closeGraphicCSSClass);
n.appendChild(g);SimileAjax.WindowManager.registerEventWithObject(g,"click",h,"close");(function(){var g=SimileAjax.Graphics.getWindowDimensions(),h=g.w,k=g.h,g=Math.ceil(d.arrowGraphicWidth/2),m=function(a){var b=document.createElement("div");b.className=j(d.arrowGraphicCSSClassPrefix+"point-"+a);n.appendChild(b);return b};if(a-g-d.borderGraphicSize-d.extraPadding>0&&a+g+d.borderGraphicSize+d.extraPadding<h){var l=a-Math.round(c/2),l=a<h/2?Math.max(l,d.extraPadding+d.borderGraphicSize):Math.min(l,
h-d.extraPadding-d.borderGraphicSize-c);if(f&&f=="top"||!f&&b-d.arrowGraphicTargetOffset-e-d.borderGraphicSize-d.extraPadding>0){k=m("down");k.style.left=a-g-l+"px";i.style.left=l+"px";i.style.top=b-d.arrowGraphicTargetOffset-e+"px";return}else if(f&&f=="bottom"||!f&&b+d.arrowGraphicTargetOffset+e+d.borderGraphicSize+d.extraPadding<k){k=m("up");k.style.left=a-g-l+"px";i.style.left=l+"px";i.style.top=b+d.arrowGraphicTargetOffset+"px";return}}h=b-Math.round(e/2);h=b<k/2?Math.max(h,d.extraPadding+d.borderGraphicSize):
Math.min(h,k-d.extraPadding-d.borderGraphicSize-e);f&&f=="left"||!f&&a-d.arrowGraphicTargetOffset-c-d.borderGraphicSize-d.extraPadding>0?(k=m("right"),k.style.top=b-g-h+"px",i.style.top=h+"px",i.style.left=a-d.arrowGraphicTargetOffset-c+"px"):(k=m("left"),k.style.top=b-g-h+"px",i.style.top=h+"px",i.style.left=a+d.arrowGraphicTargetOffset+"px")})();document.body.appendChild(i);return h};
SimileAjax.Graphics.getWindowDimensions=function(){if(typeof window.innerHeight=="number")return{w:window.innerWidth,h:window.innerHeight};else if(document.documentElement&&document.documentElement.clientHeight)return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight};else if(document.body&&document.body.clientHeight)return{w:document.body.clientWidth,h:document.body.clientHeight}};
SimileAjax.Graphics.createMessageBubble=function(a){var b=a.createElement("div");if(SimileAjax.Graphics.pngIsTranslucent){var c=a.createElement("div");c.style.height="33px";c.style.background="url("+SimileAjax.urlPrefix+"images/message-top-left.png) top left no-repeat";c.style.paddingLeft="44px";b.appendChild(c);var e=a.createElement("div");e.style.height="33px";e.style.background="url("+SimileAjax.urlPrefix+"images/message-top-right.png) top right no-repeat";c.appendChild(e);c=a.createElement("div");
c.style.background="url("+SimileAjax.urlPrefix+"images/message-left.png) top left repeat-y";c.style.paddingLeft="44px";b.appendChild(c);e=a.createElement("div");e.style.background="url("+SimileAjax.urlPrefix+"images/message-right.png) top right repeat-y";e.style.paddingRight="44px";c.appendChild(e);c=a.createElement("div");e.appendChild(c);e=a.createElement("div");e.style.height="55px";e.style.background="url("+SimileAjax.urlPrefix+"images/message-bottom-left.png) bottom left no-repeat";e.style.paddingLeft=
"44px";b.appendChild(e);a=a.createElement("div");a.style.height="55px";a.style.background="url("+SimileAjax.urlPrefix+"images/message-bottom-right.png) bottom right no-repeat";e.appendChild(a)}else b.style.border="2px solid #7777AA",b.style.padding="20px",b.style.background="white",SimileAjax.Graphics.setOpacity(b,90),c=a.createElement("div"),b.appendChild(c);return{containerDiv:b,contentDiv:c}};
SimileAjax.Graphics.createAnimation=function(a,b,c,e,f){return new SimileAjax.Graphics._Animation(a,b,c,e,f)};SimileAjax.Graphics._Animation=function(a,b,c,e,f){this.f=a;this.cont=typeof f=="function"?f:function(){};this.from=b;this.to=c;this.current=b;this.duration=e;this.start=(new Date).getTime();this.timePassed=0};SimileAjax.Graphics._Animation.prototype.run=function(){var a=this;window.setTimeout(function(){a.step()},50)};
SimileAjax.Graphics._Animation.prototype.step=function(){this.timePassed+=50;var a=(-Math.cos(this.timePassed/this.duration*Math.PI)/2+0.5)*(this.to-this.from)+this.from;try{this.f(a,a-this.current)}catch(b){}this.current=a;this.timePassed<this.duration?this.run():(this.f(this.to,0),this.cont())};
SimileAjax.Graphics.createStructuredDataCopyButton=function(a,b,c,e){var f=document.createElement("div");f.style.position="relative";f.style.display="inline";f.style.width=b+"px";f.style.height=c+"px";f.style.overflow="hidden";f.style.margin="2px";SimileAjax.Graphics.pngIsTranslucent?f.style.background="url("+a+") no-repeat":f.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a+"', sizingMethod='image')";f.innerHTML="<textarea rows='1' autocomplete='off' value='none' style='"+
(SimileAjax.Platform.browser.isIE?"filter:alpha(opacity=0)":"opacity: 0")+"' />";var d=f.firstChild;d.style.width=b+"px";d.style.height=c+"px";d.onmousedown=function(a){if((a?a:event?event:null).button==2)d.value=e(),d.select()};return f};SimileAjax.Graphics.getWidthHeight=function(a){var b;a.getBoundingClientRect==null?(b=a.offsetWidth,a=a.offsetHeight):(a=a.getBoundingClientRect(),b=Math.ceil(a.right-a.left),a=Math.ceil(a.bottom-a.top));return{width:b,height:a}};
SimileAjax.Graphics.getFontRenderingContext=function(a,b){return new SimileAjax.Graphics._FontRenderingContext(a,b)};SimileAjax.Graphics._FontRenderingContext=function(a,b){this._elmt=a;this._elmt.style.visibility="hidden";if(typeof b=="string")this._elmt.style.width=b;else if(typeof b=="number")this._elmt.style.width=b+"px"};SimileAjax.Graphics._FontRenderingContext.prototype.dispose=function(){this._elmt=null};
SimileAjax.Graphics._FontRenderingContext.prototype.update=function(){this._elmt.innerHTML="A";this._lineHeight=this._elmt.offsetHeight};SimileAjax.Graphics._FontRenderingContext.prototype.computeSize=function(a,b){var c=this._elmt;c.innerHTML=a;c.className=b===void 0?"":b;var e=SimileAjax.Graphics.getWidthHeight(c);c.className="";return e};SimileAjax.Graphics._FontRenderingContext.prototype.getLineHeight=function(){return this._lineHeight};
