SimileAjax.History={maxHistoryLength:10,historyFile:"__history__.html",enabled:!0,_initialized:!1,_listeners:new SimileAjax.ListenerQueue,_actions:[],_baseIndex:0,_currentIndex:0,_plainDocumentTitle:document.title};SimileAjax.History.formatHistoryEntryTitle=function(a){return SimileAjax.History._plainDocumentTitle+" {"+a+"}"};
SimileAjax.History.initialize=function(){if(!SimileAjax.History._initialized){if(SimileAjax.History.enabled){var a=document.createElement("iframe");a.id="simile-ajax-history";a.style.position="absolute";a.style.width="10px";a.style.height="10px";a.style.top="0px";a.style.left="0px";a.style.visibility="hidden";a.src=SimileAjax.History.historyFile+"?0";document.body.appendChild(a);SimileAjax.DOM.registerEvent(a,"load",SimileAjax.History._handleIFrameOnLoad);SimileAjax.History._iframe=a}SimileAjax.History._initialized=
!0}};SimileAjax.History.addListener=function(a){SimileAjax.History.initialize();SimileAjax.History._listeners.add(a)};SimileAjax.History.removeListener=function(a){SimileAjax.History.initialize();SimileAjax.History._listeners.remove(a)};
SimileAjax.History.addAction=function(a){SimileAjax.History.initialize();SimileAjax.History._listeners.fire("onBeforePerform",[a]);window.setTimeout(function(){try{if(a.perform(),SimileAjax.History._listeners.fire("onAfterPerform",[a]),SimileAjax.History.enabled){SimileAjax.History._actions=SimileAjax.History._actions.slice(0,SimileAjax.History._currentIndex-SimileAjax.History._baseIndex);SimileAjax.History._actions.push(a);SimileAjax.History._currentIndex++;var b=SimileAjax.History._actions.length-
SimileAjax.History.maxHistoryLength;if(b>0)SimileAjax.History._actions=SimileAjax.History._actions.slice(b),SimileAjax.History._baseIndex+=b;try{SimileAjax.History._iframe.contentWindow.location.search="?"+SimileAjax.History._currentIndex}catch(d){var c=SimileAjax.History.formatHistoryEntryTitle(a.label);document.title=c}}}catch(e){SimileAjax.Debug.exception(e,"Error adding action {"+a.label+"} to history")}},0)};
SimileAjax.History.addLengthyAction=function(a,b,d){SimileAjax.History.addAction({perform:a,undo:b,label:d,uiLayer:SimileAjax.WindowManager.getBaseLayer(),lengthy:!0})};
SimileAjax.History._handleIFrameOnLoad=function(){try{var a=SimileAjax.History._iframe.contentWindow.location.search,b=a.length==0?0:Math.max(0,parseInt(a.substr(1))),d=function(){var a=b-SimileAjax.History._currentIndex;SimileAjax.History._currentIndex+=a;SimileAjax.History._baseIndex+=a;SimileAjax.History._iframe.contentWindow.location.search="?"+b};if(b<SimileAjax.History._currentIndex)SimileAjax.History._listeners.fire("onBeforeUndoSeveral",[]),window.setTimeout(function(){for(;SimileAjax.History._currentIndex>
b&&SimileAjax.History._currentIndex>SimileAjax.History._baseIndex;){SimileAjax.History._currentIndex--;var a=SimileAjax.History._actions[SimileAjax.History._currentIndex-SimileAjax.History._baseIndex];try{a.undo()}catch(c){SimileAjax.Debug.exception(c,"History: Failed to undo action {"+a.label+"}")}}SimileAjax.History._listeners.fire("onAfterUndoSeveral",[]);d()},0);else if(b>SimileAjax.History._currentIndex)SimileAjax.History._listeners.fire("onBeforeRedoSeveral",[]),window.setTimeout(function(){for(;SimileAjax.History._currentIndex<
b&&SimileAjax.History._currentIndex-SimileAjax.History._baseIndex<SimileAjax.History._actions.length;){var a=SimileAjax.History._actions[SimileAjax.History._currentIndex-SimileAjax.History._baseIndex];try{a.perform()}catch(c){SimileAjax.Debug.exception(c,"History: Failed to redo action {"+a.label+"}")}SimileAjax.History._currentIndex++}SimileAjax.History._listeners.fire("onAfterRedoSeveral",[]);d()},0);else{var c=SimileAjax.History._currentIndex-SimileAjax.History._baseIndex-1,e=c>=0&&c<SimileAjax.History._actions.length?
SimileAjax.History.formatHistoryEntryTitle(SimileAjax.History._actions[c].label):SimileAjax.History._plainDocumentTitle;SimileAjax.History._iframe.contentWindow.document.title=e;document.title=e}}catch(f){}};SimileAjax.History.getNextUndoAction=function(){try{return SimileAjax.History._actions[SimileAjax.History._currentIndex-SimileAjax.History._baseIndex-1]}catch(a){return null}};
SimileAjax.History.getNextRedoAction=function(){try{return SimileAjax.History._actions[SimileAjax.History._currentIndex-SimileAjax.History._baseIndex]}catch(a){return null}};
