Timeline.Geochrono={};Timeline.Geochrono.eons=[{name:"Proterozoic",start:2500},{name:"Phanerozoic",start:542}];Timeline.Geochrono.eras=[{name:"Paleoarchean",start:3600},{name:"Mesoarchean",start:3200},{name:"Neoarchean",start:2800},{name:"Paleoproterozoic",start:2500},{name:"Mesoproterozoic",start:1600},{name:"Neoproterozoic",start:1E3},{name:"Paleozoic",start:542},{name:"Mesozoic",start:251},{name:"Cenozoic",start:65.5}];
Timeline.Geochrono.periods=[{name:"Siderian",start:2500},{name:"Rhyacian",start:2300},{name:"Orosirian",start:2050},{name:"Statherian",start:1800},{name:"Calymmian",start:1600},{name:"Ectasian",start:1400},{name:"Stenian",start:1200},{name:"Tonian",start:1E3},{name:"Cryogenian",start:850},{name:"Ediacaran",start:600},{name:"Cambrian",start:542},{name:"Ordovician",start:488.3},{name:"Silurian",start:443.7},{name:"Devonian",start:416},{name:"Carboniferous",start:359.2},{name:"Permian",start:299},{name:"Triassic",
start:251},{name:"Jurassic",start:199.6},{name:"Cretaceous",start:145.5},{name:"Paleogene",start:65.5},{name:"Neogene",start:23.03}];
Timeline.Geochrono.epoches=[{name:"Lower Cambrian",start:542},{name:"Middle Cambrian",start:513},{name:"Furongian",start:501},{name:"Lower Ordovician",start:488.3},{name:"Middle Ordovician",start:471.8},{name:"Upper Ordovician",start:460.9},{name:"Llandovery",start:443.7},{name:"Wenlock",start:428.2},{name:"Ludlow",start:422.9},{name:"Pridoli",start:418.7},{name:"Lower Devonian",start:416},{name:"Middle Devonian",start:397.5},{name:"Upper Devonian",start:385.3},{name:"Mississippian",start:359.2},
{name:"Pennsylvanian",start:318.1},{name:"Cisuralian",start:299},{name:"Guadalupian",start:270.6},{name:"Lopingian",start:260.4},{name:"Lower Triassic",start:251},{name:"Middle Triassic",start:245},{name:"Upper Triassic",start:228},{name:"Lower Jurassic",start:199.6},{name:"Middle Jurassic",start:175.6},{name:"Upper Jurassic",start:161.2},{name:"Lower Cretaceous",start:145.5},{name:"Upper Cretaceous",start:99.6},{name:"Paleocene",start:65.5},{name:"Eocene",start:55.8},{name:"Oligocene",start:33.9},
{name:"Miocene",start:23.03},{name:"Pliocene",start:5.332},{name:"Pleistocene",start:1.806},{name:"Holocene",start:0.012}];
Timeline.Geochrono.ages=[{name:"-",start:542},{name:"-",start:513},{name:"Paibian",start:501},{name:"Tremadocian",start:488.3},{name:"-",start:478.6},{name:"-",start:471.8},{name:"Darriwilian",start:468.1},{name:"-",start:460.9},{name:"-",start:455.8},{name:"Hirnantian",start:445.6},{name:"Rhuddanian",start:443.7},{name:"Aeronian",start:439},{name:"Telychian",start:436.1},{name:"Sheinwoodian",start:428.2},{name:"Homerian",start:426.2},{name:"Gorstian",start:422.9},{name:"Ludfordian",start:421.3},
{name:"-",start:418.7},{name:"Lochkovian",start:416},{name:"Pragian",start:411.2},{name:"Emsian",start:407},{name:"Eifelian",start:397.5},{name:"Givetian",start:391.8},{name:"Frasnian",start:385.3},{name:"Famennian",start:374.5},{name:"Tournaisian",start:359.2},{name:"Visean",start:345.3},{name:"Serpukhovian",start:326.4},{name:"Bashkirian",start:318.1},{name:"Moscovian",start:311.7},{name:"Kazimovian",start:306.5},{name:"Gzhelian",start:303.9},{name:"Asselian",start:299},{name:"Sakmarian",start:294.6},
{name:"Artinskian",start:284.4},{name:"Kungurian",start:275.6},{name:"Roadian",start:270.6},{name:"Wordian",start:268},{name:"Capitanian",start:265.8},{name:"Wuchiapingian",start:260.4},{name:"Changhsingian",start:253.8},{name:"Induan",start:251},{name:"Olenekian",start:249.7},{name:"Anisian",start:245},{name:"Ladinian",start:237},{name:"Carnian",start:228},{name:"Norian",start:216.5},{name:"Rhaetian",start:203.6},{name:"Hettangian",start:199.6},{name:"Sinemurian",start:196.5},{name:"Pliensbachian",
start:189.6},{name:"Toarcian",start:183},{name:"Aalenian",start:175.6},{name:"Bajocian",start:171.6},{name:"Bathonian",start:167.7},{name:"Callovian",start:164.7},{name:"Oxfordian",start:161.2},{name:"Kimmeridgian",start:155},{name:"Tithonian",start:150.8},{name:"Berriasian",start:145.5},{name:"Valanginian",start:140.2},{name:"Hauterivian",start:136.4},{name:"Barremian",start:130},{name:"Aptian",start:125},{name:"Albian",start:112},{name:"Cenomanian",start:99.6},{name:"Turonian",start:93.5},{name:"Coniacian",
start:89.3},{name:"Santonian",start:85.8},{name:"Campanian",start:83.5},{name:"Maastrichtian",start:70.6},{name:"Danian",start:65.5},{name:"Selandian",start:61.7},{name:"Thanetian",start:58.7},{name:"Ypresian",start:55.8},{name:"Lutetian",start:48.6},{name:"Bartonian",start:40.4},{name:"Priabonian",start:37.2},{name:"Rupelian",start:33.9},{name:"Chattian",start:28.4},{name:"Aquitanian",start:23.03},{name:"Burdigalian",start:20.43},{name:"Langhian",start:15.97},{name:"Serravallian",start:13.65},{name:"Tortonian",
start:11.608},{name:"Messinian",start:7.246},{name:"Zanclean",start:5.332},{name:"Piacenzian",start:3.6},{name:"Gelasian",start:2.588}];
Timeline.Geochrono.createBandInfo=function(a){var b="theme"in a?a.theme:Timeline.getDefaultTheme(),c="eventSource"in a?a.eventSource:null,d=new Timeline.LinearEther({centersOn:"date"in a?a.date:Timeline.GeochronoUnit.makeDefaultValue(),interval:1,pixelsPerInterval:a.intervalPixels}),e=new Timeline.GeochronoEtherPainter({intervalUnit:a.intervalUnit,multiple:"multiple"in a?a.multiple:1,align:a.align,theme:b}),b={theme:b};if("trackHeight"in a)b.trackHeight=a.trackHeight;if("trackGap"in a)b.trackGap=
a.trackGap;b="overview"in a&&a.overview?new Timeline.OverviewEventPainter(b):new Timeline.DetailedEventPainter(b);return{width:a.width,eventSource:c,timeZone:"timeZone"in a?a.timeZone:0,ether:d,etherPainter:e,eventPainter:b}};
