Timeline._Band=function(b,a,c){if(b.autoWidth&&typeof a.width=="string")a.width=a.width.indexOf("%")>-1?0:parseInt(a.width);this._timeline=b;this._bandInfo=a;this._index=c;this._locale="locale"in a?a.locale:Timeline.getDefaultLocale();this._timeZone="timeZone"in a?a.timeZone:0;this._labeller="labeller"in a?a.labeller:"createLabeller"in b.getUnit()?b.getUnit().createLabeller(this._locale,this._timeZone):new Timeline.GregorianDateLabeller(this._locale,this._timeZone);this._theme=a.theme;this._zoomIndex=
"zoomIndex"in a?a.zoomIndex:0;this._zoomSteps="zoomSteps"in a?a.zoomSteps:null;this._changing=this._dragging=!1;this._scrollSpeed=this._originalScrollSpeed=5;this._onScrollListeners=[];var d=this;this._syncWithBand=null;this._syncWithBandHandler=function(){d._onHighlightBandScroll()};this._selectorListener=function(){d._onHighlightBandScroll()};var e=this._timeline.getDocument().createElement("div");e.className="timeline-band-input";this._timeline.addDiv(e);this._keyboardInput=document.createElement("input");
this._keyboardInput.type="text";e.appendChild(this._keyboardInput);SimileAjax.DOM.registerEventWithObject(this._keyboardInput,"keydown",this,"_onKeyDown");SimileAjax.DOM.registerEventWithObject(this._keyboardInput,"keyup",this,"_onKeyUp");this._div=this._timeline.getDocument().createElement("div");this._div.id="timeline-band-"+c;this._div.className="timeline-band timeline-band-"+c;this._timeline.addDiv(this._div);SimileAjax.DOM.registerEventWithObject(this._div,"mousedown",this,"_onMouseDown");SimileAjax.DOM.registerEventWithObject(this._div,
"mousemove",this,"_onMouseMove");SimileAjax.DOM.registerEventWithObject(this._div,"mouseup",this,"_onMouseUp");SimileAjax.DOM.registerEventWithObject(this._div,"mouseout",this,"_onMouseOut");SimileAjax.DOM.registerEventWithObject(this._div,"dblclick",this,"_onDblClick");c=this._theme!=null?this._theme.mouseWheel:"scroll";if(c==="zoom"||c==="scroll"||this._zoomSteps)SimileAjax.Platform.browser.isFirefox?SimileAjax.DOM.registerEventWithObject(this._div,"DOMMouseScroll",this,"_onMouseScroll"):SimileAjax.DOM.registerEventWithObject(this._div,
"mousewheel",this,"_onMouseScroll");this._innerDiv=this._timeline.getDocument().createElement("div");this._innerDiv.className="timeline-band-inner";this._div.appendChild(this._innerDiv);this._ether=a.ether;a.ether.initialize(this,b);this._etherPainter=a.etherPainter;a.etherPainter.initialize(this,b);if(this._eventSource=a.eventSource)this._eventListener={onAddMany:function(){d._onAddMany()},onClear:function(){d._onClear()}},this._eventSource.addListener(this._eventListener);this._eventPainter=a.eventPainter;
this._eventTrackIncrement=this._eventTracksNeeded=0;a.eventPainter.initialize(this,b);this._decorators="decorators"in a?a.decorators:[];for(a=0;a<this._decorators.length;a++)this._decorators[a].initialize(this,b)};Timeline._Band.SCROLL_MULTIPLES=5;
Timeline._Band.prototype.dispose=function(){this.closeBubble();if(this._eventSource)this._eventSource.removeListener(this._eventListener),this._eventSource=this._eventListener=null;this._keyboardInput=this._innerDiv=this._div=this._selectorListener=this._syncWithBandHandler=this._onScrollListeners=this._decorators=this._eventPainter=this._etherPainter=this._ether=this._labeller=this._bandInfo=this._timeline=null};Timeline._Band.prototype.addOnScrollListener=function(b){this._onScrollListeners.push(b)};
Timeline._Band.prototype.removeOnScrollListener=function(b){for(var a=0;a<this._onScrollListeners.length;a++)if(this._onScrollListeners[a]==b){this._onScrollListeners.splice(a,1);break}};Timeline._Band.prototype.setSyncWithBand=function(b,a){this._syncWithBand&&this._syncWithBand.removeOnScrollListener(this._syncWithBandHandler);this._syncWithBand=b;this._syncWithBand.addOnScrollListener(this._syncWithBandHandler);this._highlight=a;this._positionHighlight()};Timeline._Band.prototype.getLocale=function(){return this._locale};
Timeline._Band.prototype.getTimeZone=function(){return this._timeZone};Timeline._Band.prototype.getLabeller=function(){return this._labeller};Timeline._Band.prototype.getIndex=function(){return this._index};Timeline._Band.prototype.getEther=function(){return this._ether};Timeline._Band.prototype.getEtherPainter=function(){return this._etherPainter};Timeline._Band.prototype.getEventSource=function(){return this._eventSource};Timeline._Band.prototype.getEventPainter=function(){return this._eventPainter};
Timeline._Band.prototype.getTimeline=function(){return this._timeline};Timeline._Band.prototype.updateEventTrackInfo=function(b,a){this._eventTrackIncrement=a;if(b>this._eventTracksNeeded)this._eventTracksNeeded=b};
Timeline._Band.prototype.checkAutoWidth=function(){if(this._timeline.autoWidth){var b=this._eventPainter.getType()=="overview",a=Math.ceil((this._eventTracksNeeded+(b?this._theme.event.overviewTrack.autoWidthMargin:this._theme.event.track.autoWidthMargin))*this._eventTrackIncrement);a+=b?this._theme.event.overviewTrack.offset:this._theme.event.track.offset;b=this._bandInfo;if(a!=b.width)b.width=a}};Timeline._Band.prototype.layout=function(){this.paint()};
Timeline._Band.prototype.paint=function(){this._etherPainter.paint();this._paintDecorators();this._paintEvents()};Timeline._Band.prototype.softLayout=function(){this.softPaint()};Timeline._Band.prototype.softPaint=function(){this._etherPainter.softPaint();this._softPaintDecorators();this._softPaintEvents()};
Timeline._Band.prototype.setBandShiftAndWidth=function(b,a){var c=this._keyboardInput.parentNode,d=b+Math.floor(a/2);this._timeline.isHorizontal()?(this._div.style.top=b+"px",this._div.style.height=a+"px",c.style.top=d+"px",c.style.left="-1em"):(this._div.style.left=b+"px",this._div.style.width=a+"px",c.style.left=d+"px",c.style.top="-1em")};Timeline._Band.prototype.getViewWidth=function(){return this._timeline.isHorizontal()?this._div.offsetHeight:this._div.offsetWidth};
Timeline._Band.prototype.setViewLength=function(b){this._viewLength=b;this._recenterDiv();this._onChanging()};Timeline._Band.prototype.getViewLength=function(){return this._viewLength};Timeline._Band.prototype.getTotalViewLength=function(){return Timeline._Band.SCROLL_MULTIPLES*this._viewLength};Timeline._Band.prototype.getViewOffset=function(){return this._viewOffset};Timeline._Band.prototype.getMinDate=function(){return this._ether.pixelOffsetToDate(this._viewOffset)};
Timeline._Band.prototype.getMaxDate=function(){return this._ether.pixelOffsetToDate(this._viewOffset+Timeline._Band.SCROLL_MULTIPLES*this._viewLength)};Timeline._Band.prototype.getMinVisibleDate=function(){return this._ether.pixelOffsetToDate(0)};Timeline._Band.prototype.getMinVisibleDateAfterDelta=function(b){return this._ether.pixelOffsetToDate(b)};Timeline._Band.prototype.getMaxVisibleDate=function(){return this._ether.pixelOffsetToDate(this._viewLength)};
Timeline._Band.prototype.getMaxVisibleDateAfterDelta=function(b){return this._ether.pixelOffsetToDate(this._viewLength+b)};Timeline._Band.prototype.getCenterVisibleDate=function(){return this._ether.pixelOffsetToDate(this._viewLength/2)};Timeline._Band.prototype.setMinVisibleDate=function(b){this._changing||this._moveEther(Math.round(-this._ether.dateToPixelOffset(b)))};Timeline._Band.prototype.setMaxVisibleDate=function(b){this._changing||this._moveEther(Math.round(this._viewLength-this._ether.dateToPixelOffset(b)))};
Timeline._Band.prototype.setCenterVisibleDate=function(b){this._changing||this._moveEther(Math.round(this._viewLength/2-this._ether.dateToPixelOffset(b)))};Timeline._Band.prototype.dateToPixelOffset=function(b){return this._ether.dateToPixelOffset(b)-this._viewOffset};Timeline._Band.prototype.pixelOffsetToDate=function(b){return this._ether.pixelOffsetToDate(b+this._viewOffset)};
Timeline._Band.prototype.createLayerDiv=function(b,a){var c=this._timeline.getDocument().createElement("div");c.className="timeline-band-layer"+(typeof a=="string"?" "+a:"");c.style.zIndex=b;this._innerDiv.appendChild(c);var d=this._timeline.getDocument().createElement("div");d.className="timeline-band-layer-inner";d.style.cursor=SimileAjax.Platform.browser.isIE?"move":"-moz-grab";c.appendChild(d);return d};Timeline._Band.prototype.removeLayerDiv=function(b){this._innerDiv.removeChild(b.parentNode)};
Timeline._Band.prototype.scrollToCenter=function(b,a){var c=this._ether.dateToPixelOffset(b);c<-this._viewLength/2?this.setCenterVisibleDate(this.pixelOffsetToDate(c+this._viewLength)):c>3*this._viewLength/2&&this.setCenterVisibleDate(this.pixelOffsetToDate(c-this._viewLength));this._autoScroll(Math.round(this._viewLength/2-this._ether.dateToPixelOffset(b)),a)};
Timeline._Band.prototype.showBubbleForEvent=function(b){var a=this.getEventSource().getEvent(b);if(a){var c=this;this.scrollToCenter(a.getStart(),function(){c._eventPainter.showBubble(a)})}};Timeline._Band.prototype.zoom=function(b,a){if(this._zoomSteps){a+=this._viewOffset;var c=this._ether.pixelOffsetToDate(a);this._etherPainter.zoom(this._ether.zoom(b));this._moveEther(Math.round(-this._ether.dateToPixelOffset(c)));this._moveEther(a)}};
Timeline._Band.prototype._onMouseDown=function(b,a){this.closeBubble();this._dragging=!0;this._dragX=a.clientX;this._dragY=a.clientY};Timeline._Band.prototype._onMouseMove=function(b,a){if(this._dragging){var c=a.clientX-this._dragX,d=a.clientY-this._dragY;this._dragX=a.clientX;this._dragY=a.clientY;this._moveEther(this._timeline.isHorizontal()?c:d);this._positionHighlight()}};Timeline._Band.prototype._onMouseUp=function(){this._dragging=!1;this._keyboardInput.focus()};
Timeline._Band.prototype._onMouseOut=function(b,a){var c=SimileAjax.DOM.getEventRelativeCoordinates(a,b);c.x+=this._viewOffset;if(c.x<0||c.x>b.offsetWidth||c.y<0||c.y>b.offsetHeight)this._dragging=!1};
Timeline._Band.prototype._onMouseScroll=function(b,a){var c=new Date,c=c.getTime();if(!this._lastScrollTime||c-this._lastScrollTime>50){this._lastScrollTime=c;c=0;a.wheelDelta?c=a.wheelDelta/120:a.detail&&(c=-a.detail/3);var d=this._theme.mouseWheel;if(this._zoomSteps||d==="zoom"){if(d=SimileAjax.DOM.getEventRelativeCoordinates(a,b),c!=0){var e;c>0&&(e=!0);c<0&&(e=!1);this._timeline.zoom(e,d.x,d.y,b)}}else d==="scroll"&&this._moveEther(50*(c<0?-1:1))}a.stopPropagation&&a.stopPropagation();a.cancelBubble=
!0;a.preventDefault&&a.preventDefault();a.returnValue=!1};Timeline._Band.prototype._onDblClick=function(b,a){this._autoScroll(-(SimileAjax.DOM.getEventRelativeCoordinates(a,b).x-(this._viewLength/2-this._viewOffset)))};
Timeline._Band.prototype._onKeyDown=function(b,a){if(!this._dragging){switch(a.keyCode){case 27:break;case 37:case 38:this._scrollSpeed=Math.min(50,Math.abs(this._scrollSpeed*1.05));this._moveEther(this._scrollSpeed);break;case 39:case 40:this._scrollSpeed=-Math.min(50,Math.abs(this._scrollSpeed*1.05));this._moveEther(this._scrollSpeed);break;default:return!0}this.closeBubble();SimileAjax.DOM.cancelEvent(a);return!1}return!0};
Timeline._Band.prototype._onKeyUp=function(b,a){if(!this._dragging){this._scrollSpeed=this._originalScrollSpeed;switch(a.keyCode){case 35:this.setCenterVisibleDate(this._eventSource.getLatestDate());break;case 36:this.setCenterVisibleDate(this._eventSource.getEarliestDate());break;case 33:this._autoScroll(this._timeline.getPixelLength());break;case 34:this._autoScroll(-this._timeline.getPixelLength());break;default:return!0}this.closeBubble();SimileAjax.DOM.cancelEvent(a);return!1}return!0};
Timeline._Band.prototype._autoScroll=function(b,a){var c=this;SimileAjax.Graphics.createAnimation(function(a,b){c._moveEther(b)},0,b,1E3,a).run()};
Timeline._Band.prototype._moveEther=function(b){this.closeBubble();if(this._timeline.shiftOK(this._index,b))this._viewOffset+=b,this._ether.shiftPixels(-b),this._timeline.isHorizontal()?this._div.style.left=this._viewOffset+"px":this._div.style.top=this._viewOffset+"px",this._viewOffset>-this._viewLength*0.5||this._viewOffset<-this._viewLength*(Timeline._Band.SCROLL_MULTIPLES-1.5)?this._recenterDiv():this.softLayout(),this._onChanging()};
Timeline._Band.prototype._onChanging=function(){this._changing=!0;this._fireOnScroll();this._setSyncWithBandDate();this._changing=!1};Timeline._Band.prototype.busy=function(){return this._changing};Timeline._Band.prototype._fireOnScroll=function(){for(var b=0;b<this._onScrollListeners.length;b++)this._onScrollListeners[b](this)};Timeline._Band.prototype._setSyncWithBandDate=function(){this._syncWithBand&&this._syncWithBand.setCenterVisibleDate(this._ether.pixelOffsetToDate(this.getViewLength()/2))};
Timeline._Band.prototype._onHighlightBandScroll=function(){if(this._syncWithBand){var b=this._ether.dateToPixelOffset(this._syncWithBand.getCenterVisibleDate());this._moveEther(Math.round(this._viewLength/2-b));this._highlight&&this._etherPainter.setHighlight(this._syncWithBand.getMinVisibleDate(),this._syncWithBand.getMaxVisibleDate())}};Timeline._Band.prototype._onAddMany=function(){this._paintEvents()};Timeline._Band.prototype._onClear=function(){this._paintEvents()};
Timeline._Band.prototype._positionHighlight=function(){if(this._syncWithBand){var b=this._syncWithBand.getMinVisibleDate(),a=this._syncWithBand.getMaxVisibleDate();this._highlight&&this._etherPainter.setHighlight(b,a)}};
Timeline._Band.prototype._recenterDiv=function(){this._viewOffset=-this._viewLength*(Timeline._Band.SCROLL_MULTIPLES-1)/2;this._timeline.isHorizontal()?(this._div.style.left=this._viewOffset+"px",this._div.style.width=Timeline._Band.SCROLL_MULTIPLES*this._viewLength+"px"):(this._div.style.top=this._viewOffset+"px",this._div.style.height=Timeline._Band.SCROLL_MULTIPLES*this._viewLength+"px");this.layout()};Timeline._Band.prototype._paintEvents=function(){this._eventPainter.paint()};
Timeline._Band.prototype._softPaintEvents=function(){this._eventPainter.softPaint()};Timeline._Band.prototype._paintDecorators=function(){for(var b=0;b<this._decorators.length;b++)this._decorators[b].paint()};Timeline._Band.prototype._softPaintDecorators=function(){for(var b=0;b<this._decorators.length;b++)this._decorators[b].softPaint()};Timeline._Band.prototype.closeBubble=function(){SimileAjax.WindowManager.cancelPopups()};
