Timeline.CompactEventPainter=function(a){this._params=a;this._onSelectListeners=[];this._frc=this._highlightMatcher=this._filterMatcher=null;this._eventIdToElmt={}};Timeline.CompactEventPainter.prototype.initialize=function(a,b){this._band=a;this._timeline=b;this._eventIdToElmt=this._highlightLayer=this._lineLayer=this._eventLayer=this._backLayer=null};Timeline.CompactEventPainter.prototype.addOnSelectListener=function(a){this._onSelectListeners.push(a)};
Timeline.CompactEventPainter.prototype.removeOnSelectListener=function(a){for(var b=0;b<this._onSelectListeners.length;b++)if(this._onSelectListeners[b]==a){this._onSelectListeners.splice(b,1);break}};Timeline.CompactEventPainter.prototype.getFilterMatcher=function(){return this._filterMatcher};Timeline.CompactEventPainter.prototype.setFilterMatcher=function(a){this._filterMatcher=a};Timeline.CompactEventPainter.prototype.getHighlightMatcher=function(){return this._highlightMatcher};
Timeline.CompactEventPainter.prototype.setHighlightMatcher=function(a){this._highlightMatcher=a};
Timeline.CompactEventPainter.prototype.paint=function(){var a=this._band.getEventSource();if(a!=null){this._eventIdToElmt={};this._prepareForPainting();var b=this._params.theme,c=b.event,b={trackOffset:"trackOffset"in this._params?this._params.trackOffset:10,trackHeight:"trackHeight"in this._params?this._params.trackHeight:10,tapeHeight:b.event.tape.height,tapeBottomMargin:"tapeBottomMargin"in this._params?this._params.tapeBottomMargin:2,labelBottomMargin:"labelBottomMargin"in this._params?this._params.labelBottomMargin:
5,labelRightMargin:"labelRightMargin"in this._params?this._params.labelRightMargin:5,defaultIcon:c.instant.icon,defaultIconWidth:c.instant.iconWidth,defaultIconHeight:c.instant.iconHeight,customIconWidth:"iconWidth"in this._params?this._params.iconWidth:c.instant.iconWidth,customIconHeight:"iconHeight"in this._params?this._params.iconHeight:c.instant.iconHeight,iconLabelGap:"iconLabelGap"in this._params?this._params.iconLabelGap:2,iconBottomMargin:"iconBottomMargin"in this._params?this._params.iconBottomMargin:
2};"compositeIcon"in this._params?(b.compositeIcon=this._params.compositeIcon,b.compositeIconWidth=this._params.compositeIconWidth||b.customIconWidth,b.compositeIconHeight=this._params.compositeIconHeight||b.customIconHeight):(b.compositeIcon=b.defaultIcon,b.compositeIconWidth=b.defaultIconWidth,b.compositeIconHeight=b.defaultIconHeight);b.defaultStackIcon="icon"in this._params.stackConcurrentPreciseInstantEvents?this._params.stackConcurrentPreciseInstantEvents.icon:b.defaultIcon;b.defaultStackIconWidth=
"iconWidth"in this._params.stackConcurrentPreciseInstantEvents?this._params.stackConcurrentPreciseInstantEvents.iconWidth:b.defaultIconWidth;b.defaultStackIconHeight="iconHeight"in this._params.stackConcurrentPreciseInstantEvents?this._params.stackConcurrentPreciseInstantEvents.iconHeight:b.defaultIconHeight;var d=this._band.getMinDate(),h=this._band.getMaxDate(),g=this._filterMatcher!=null?this._filterMatcher:function(){return!0},c=this._highlightMatcher!=null?this._highlightMatcher:function(){return-1},
h=a.getEventIterator(d,h),a="stackConcurrentPreciseInstantEvents"in this._params&&typeof this._params.stackConcurrentPreciseInstantEvents=="object";if("collapseConcurrentPreciseInstantEvents"in this._params&&this._params.collapseConcurrentPreciseInstantEvents||a){for(var d=[],e=null;h.hasNext();){var i=h.next();g(i)&&(!i.isInstant()||i.isImprecise()?this.paintEvent(i,b,this._params.theme,c(i)):e!=null&&e.getStart().getTime()==i.getStart().getTime()?d[d.length-1].push(i):(d.push([i]),e=i))}for(g=0;g<
d.length;g++)if(h=d[g],h.length==1)this.paintEvent(h[0],b,this._params.theme,c(i));else{for(var e=-1,f=0;e<0&&f<h.length;f++)e=c(h[f]);a?this.paintStackedPreciseInstantEvents(h,b,this._params.theme,e):this.paintCompositePreciseInstantEvents(h,b,this._params.theme,e)}}else for(;h.hasNext();)i=h.next(),g(i)&&this.paintEvent(i,b,this._params.theme,c(i));this._highlightLayer.style.display="block";this._lineLayer.style.display="block";this._eventLayer.style.display="block"}};
Timeline.CompactEventPainter.prototype.softPaint=function(){};
Timeline.CompactEventPainter.prototype._prepareForPainting=function(){var a=this._band;if(this._backLayer==null){this._backLayer=this._band.createLayerDiv(0,"timeline-band-events");this._backLayer.style.visibility="hidden";var b=document.createElement("span");b.className="timeline-event-label";this._backLayer.appendChild(b);this._frc=SimileAjax.Graphics.getFontRenderingContext(b)}this._frc.update();this._tracks=[];this._highlightLayer!=null&&a.removeLayerDiv(this._highlightLayer);this._highlightLayer=
a.createLayerDiv(105,"timeline-band-highlights");this._highlightLayer.style.display="none";this._lineLayer!=null&&a.removeLayerDiv(this._lineLayer);this._lineLayer=a.createLayerDiv(110,"timeline-band-lines");this._lineLayer.style.display="none";this._eventLayer!=null&&a.removeLayerDiv(this._eventLayer);this._eventLayer=a.createLayerDiv(115,"timeline-band-events");this._eventLayer.style.display="none"};
Timeline.CompactEventPainter.prototype.paintEvent=function(a,b,c,d){a.isInstant()?this.paintInstantEvent(a,b,c,d):this.paintDurationEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintInstantEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseInstantEvent(a,b,c,d):this.paintPreciseInstantEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintDurationEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseDurationEvent(a,b,c,d):this.paintPreciseDurationEvent(a,b,c,d)};
Timeline.CompactEventPainter.prototype.paintPreciseInstantEvent=function(a,b,c,d){var h={tooltip:a.getProperty("tooltip")||a.getText()},g={url:a.getIcon()};g.url==null?(g.url=b.defaultIcon,g.width=b.defaultIconWidth,g.height=b.defaultIconHeight,g.className="timeline-event-icon-default"):(g.width=a.getProperty("iconWidth")||b.customIconWidth,g.height=a.getProperty("iconHeight")||b.customIconHeight);var e={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},i=this.paintTapeIconLabel(a.getStart(),
h,null,g,e,b,c,d),f=this,b=function(b,c){return f._onClickInstantEvent(i.iconElmtData.elmt,c,a)};SimileAjax.DOM.registerEvent(i.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(i.labelElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=i.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintCompositePreciseInstantEvents=function(a,b,c,d){for(var h=a[0],g=[],e=0;e<a.length;e++)g.push(a[e].getProperty("tooltip")||a[e].getText());var g={tooltip:g.join("; ")},e={url:b.compositeIcon,width:b.compositeIconWidth,height:b.compositeIconHeight,className:"timeline-event-icon-composite"},i={text:String.substitute(this._params.compositeEventLabelTemplate,[a.length])},f=this.paintTapeIconLabel(h.getStart(),g,null,e,i,b,c,d),j=this,b=function(b,c){return j._onClickMultiplePreciseInstantEvent(f.iconElmtData.elmt,
c,a)};SimileAjax.DOM.registerEvent(f.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(f.labelElmtData.elmt,"mousedown",b);for(e=0;e<a.length;e++)this._eventIdToElmt[a[e].getID()]=f.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintStackedPreciseInstantEvents=function(a,b,c){var d="limit"in this._params.stackConcurrentPreciseInstantEvents?this._params.stackConcurrentPreciseInstantEvents.limit:10,h="moreMessageTemplate"in this._params.stackConcurrentPreciseInstantEvents?this._params.stackConcurrentPreciseInstantEvents.moreMessageTemplate:"%0 More Events",g=d<=a.length-2,e=this._band,i=function(a){var c={url:a.getIcon()};c.url==null?(c.url=b.defaultStackIcon,c.width=b.defaultStackIconWidth,
c.height=b.defaultStackIconHeight,c.className="timeline-event-icon-stack timeline-event-icon-default"):(c.width=a.getProperty("iconWidth")||b.customIconWidth,c.height=a.getProperty("iconHeight")||b.customIconHeight,c.className="timeline-event-icon-stack");return c},f=i(a[0]),j=0,n=0,l=0,p=0,q=[],k=0;for(;k<a.length&&(!g||k<d);k++){var m=a[k],o=m.getText(),m=i(m),s=this._frc.computeSize(o),o={text:o,iconData:m,labelSize:s,iconLeft:f.width+k*5-m.width};o.labelLeft=f.width+k*5+b.iconLabelGap;o.top=l;
q.push(o);j=Math.min(j,o.iconLeft);l+=s.height;n=Math.max(n,o.labelLeft+s.width);p=Math.max(p,o.top+m.height)}if(g){var w=String.substitute(h,[a.length-d]),u=this._frc.computeSize(w),A=f.width+(d-1)*5+b.iconLabelGap,C=l;l+=u.height;n=Math.max(n,A+u.width)}n+=b.labelRightMargin;l+=b.labelBottomMargin;p+=b.iconBottomMargin;for(var v=function(a){return Math.round(e.dateToPixelOffset(a))}(a[0].getStart()),h=[],i=Math.ceil(Math.max(p,l)/b.trackHeight),f=f.width+(a.length-1)*5,k=0;k<i;k++)h.push({start:j,
end:f});j=Math.ceil(l/b.trackHeight);for(k=0;k<j;k++)l=h[k],l.end=Math.max(l.end,n);var x=this._fitTracks(v,h)*b.trackHeight+b.trackOffset,r=this._timeline.getDocument().createElement("div");r.className="timeline-event-icon-stack";r.style.position="absolute";r.style.overflow="visible";r.style.left=v+"px";r.style.top=x+"px";r.style.width=f+"px";r.style.height=p+"px";r.innerHTML="<div style='position: relative'></div>";this._eventLayer.appendChild(r);var t=this,B=function(){try{for(var a=parseInt(this.getAttribute("index")),
b=r.firstChild.childNodes,c=0;c<b.length;c++)b[c].style.zIndex=c==a?b.length:b.length-c}catch(d){}},n=function(b){var d=q[b],e=a[b],f=e.getProperty("tooltip")||e.getText(),g=t._paintEventLabel({tooltip:f},{text:d.text},v+d.labelLeft,x+d.top,d.labelSize.width,d.labelSize.height,c);g.elmt.setAttribute("index",b);g.elmt.onmouseover=B;var h=SimileAjax.Graphics.createTranslucentImage(d.iconData.url),f=t._timeline.getDocument().createElement("div");f.className="timeline-event-icon"+("className"in d.iconData?
" "+d.iconData.className:"");f.style.left=d.iconLeft+"px";f.style.top=d.top+"px";f.style.zIndex=q.length-b;f.appendChild(h);f.setAttribute("index",b);f.onmouseover=B;r.firstChild.appendChild(f);b=function(a,b){return t._onClickInstantEvent(g.elmt,b,e)};SimileAjax.DOM.registerEvent(f,"mousedown",b);SimileAjax.DOM.registerEvent(g.elmt,"mousedown",b);t._eventIdToElmt[e.getID()]=f},k=0;for(;k<q.length;k++)n(k);if(g){var y=a.slice(d),z=this._paintEventLabel({tooltip:w},{text:w},v+A,x+C,u.width,u.height,
c);SimileAjax.DOM.registerEvent(z.elmt,"mousedown",function(a,b){return t._onClickMultiplePreciseInstantEvent(z.elmt,b,y)});for(k=0;k<y.length;k++)this._eventIdToElmt[y[k].getID()]=z.elmt}};
Timeline.CompactEventPainter.prototype.paintImpreciseInstantEvent=function(a,b,c,d){var h={tooltip:a.getProperty("tooltip")||a.getText()},g={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:!0},e={url:a.getIcon()};e.url==null?e=null:(e.width=a.getProperty("iconWidth")||b.customIconWidth,e.height=a.getProperty("iconHeight")||b.customIconHeight);var i={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},f=this.paintTapeIconLabel(a.getStart(),
h,g,e,i,b,c,d),j=this,b=e!=null?function(b,c){return j._onClickInstantEvent(f.iconElmtData.elmt,c,a)}:function(b,c){return j._onClickInstantEvent(f.labelElmtData.elmt,c,a)};SimileAjax.DOM.registerEvent(f.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(f.impreciseTapeElmtData.elmt,"mousedown",b);e!=null?(SimileAjax.DOM.registerEvent(f.iconElmtData.elmt,"mousedown",b),this._eventIdToElmt[a.getID()]=f.iconElmtData.elmt):this._eventIdToElmt[a.getID()]=f.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintPreciseDurationEvent=function(a,b,c,d){var h={tooltip:a.getProperty("tooltip")||a.getText()},g={start:a.getStart(),end:a.getEnd(),isInstant:!1},e={url:a.getIcon()};e.url==null?e=null:(e.width=a.getProperty("iconWidth")||b.customIconWidth,e.height=a.getProperty("iconHeight")||b.customIconHeight);var i={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},f=this.paintTapeIconLabel(a.getLatestStart(),h,g,e,i,b,c,d),j=this,b=e!=
null?function(b,c){return j._onClickInstantEvent(f.iconElmtData.elmt,c,a)}:function(b,c){return j._onClickInstantEvent(f.labelElmtData.elmt,c,a)};SimileAjax.DOM.registerEvent(f.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(f.tapeElmtData.elmt,"mousedown",b);e!=null?(SimileAjax.DOM.registerEvent(f.iconElmtData.elmt,"mousedown",b),this._eventIdToElmt[a.getID()]=f.iconElmtData.elmt):this._eventIdToElmt[a.getID()]=f.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintImpreciseDurationEvent=function(a,b,c,d){var h={tooltip:a.getProperty("tooltip")||a.getText()},g={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:!1},e={url:a.getIcon()};e.url==null?e=null:(e.width=a.getProperty("iconWidth")||b.customIconWidth,e.height=a.getProperty("iconHeight")||b.customIconHeight);var i={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},f=this.paintTapeIconLabel(a.getLatestStart(),
h,g,e,i,b,c,d),j=this,b=e!=null?function(b,c){return j._onClickInstantEvent(f.iconElmtData.elmt,c,a)}:function(b,c){return j._onClickInstantEvent(f.labelElmtData.elmt,c,a)};SimileAjax.DOM.registerEvent(f.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(f.tapeElmtData.elmt,"mousedown",b);e!=null?(SimileAjax.DOM.registerEvent(f.iconElmtData.elmt,"mousedown",b),this._eventIdToElmt[a.getID()]=f.iconElmtData.elmt):this._eventIdToElmt[a.getID()]=f.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintTapeIconLabel=function(a,b,c,d,h,g,e){var i=this._band,f=function(a){return Math.round(i.dateToPixelOffset(a))},a=f(a),j=[],n=0,l=0,p=0;if(c!=null){for(var n=g.tapeHeight+g.tapeBottomMargin,l=Math.ceil(g.tapeHeight/g.trackHeight),q=f(c.end)-a,k=f(c.start)-a,m=0;m<l;m++)j.push({start:k,end:q});p=g.trackHeight-n%g.tapeHeight}k=q=0;if(d!=null){"iconAlign"in d&&d.iconAlign=="center"&&(q=-Math.floor(d.width/2));k=q+d.width+g.iconLabelGap;if(l>0)j[l-1].end=Math.max(j[l-
1].end,k);for(m=d.height+g.iconBottomMargin+p;m>0;)j.push({start:q,end:k}),m-=g.trackHeight}var m=this._frc.computeSize(h.text),p=m.height+g.labelBottomMargin+p,o=k+m.width+g.labelRightMargin;if(l>0)j[l-1].end=Math.max(j[l-1].end,o);for(var s=0;p>0;s++)l+s<j.length?j[l+s].end=o:j.push({start:0,end:o}),p-=g.trackHeight;j=this._fitTracks(a,j)*g.trackHeight+g.trackOffset;l={};l.labelElmtData=this._paintEventLabel(b,h,a+k,j+n,m.width,m.height,e);if(c!=null){if("latestStart"in c||"earliestEnd"in c)l.impreciseTapeElmtData=
this._paintEventTape(b,c,g.tapeHeight,j,f(c.start),f(c.end),e.event.duration.impreciseColor,e.event.duration.impreciseOpacity,g,e);if(!c.isInstant&&"start"in c&&"end"in c)l.tapeElmtData=this._paintEventTape(b,c,g.tapeHeight,j,a,f("earliestEnd"in c?c.earliestEnd:c.end),c.color,100,g,e)}if(d!=null)l.iconElmtData=this._paintEventIcon(b,d,j+n,a+q,g,e);return l};
Timeline.CompactEventPainter.prototype._fitTracks=function(a,b){var c;for(c=0;c<this._tracks.length;c++){for(var d=!0,h=0;h<b.length&&c+h<this._tracks.length;h++)if(a+b[h].start<this._tracks[c+h]){d=!1;break}if(d)break}for(d=0;d<b.length;d++)this._tracks[c+d]=a+b[d].end;return c};
Timeline.CompactEventPainter.prototype._paintEventIcon=function(a,b,c,d,h){var g=SimileAjax.Graphics.createTranslucentImage(b.url),e=this._timeline.getDocument().createElement("div");e.className="timeline-event-icon"+("className"in b?" "+b.className:"");e.style.left=d+"px";e.style.top=c+"px";e.appendChild(g);if("tooltip"in a&&typeof a.tooltip=="string")e.title=a.tooltip;this._eventLayer.appendChild(e);return{left:d,top:c,width:h.iconWidth,height:h.iconHeight,elmt:e}};
Timeline.CompactEventPainter.prototype._paintEventLabel=function(a,b,c,d,h,g){var e=this._timeline.getDocument().createElement("div");e.className="timeline-event-label";e.style.left=c+"px";e.style.width=h+1+"px";e.style.top=d+"px";e.innerHTML=b.text;if("tooltip"in a&&typeof a.tooltip=="string")e.title=a.tooltip;if("color"in b&&typeof b.color=="string")e.style.color=b.color;"className"in b&&typeof b.className=="string"&&(e.className+=" "+b.className);this._eventLayer.appendChild(e);return{left:c,top:d,
width:h,height:g,elmt:e}};
Timeline.CompactEventPainter.prototype._paintEventTape=function(a,b,c,d,h,g,e,i){g-=h;var f=this._timeline.getDocument().createElement("div");f.className="timeline-event-tape";f.style.left=h+"px";f.style.top=d+"px";f.style.width=g+"px";f.style.height=c+"px";if("tooltip"in a&&typeof a.tooltip=="string")f.title=a.tooltip;if(e!=null&&typeof b.color=="string")f.style.backgroundColor=e;if("backgroundImage"in b&&typeof b.backgroundImage=="string")f.style.backgroundImage="url("+backgroundImage+")",f.style.backgroundRepeat=
"backgroundRepeat"in b&&typeof b.backgroundRepeat=="string"?b.backgroundRepeat:"repeat";SimileAjax.Graphics.setOpacity(f,i);"className"in b&&typeof b.className=="string"&&(f.className+=" "+b.className);this._eventLayer.appendChild(f);return{left:h,top:d,width:g,height:c,elmt:f}};
Timeline.CompactEventPainter.prototype._createHighlightDiv=function(a,b,c){if(a>=0){var d=this._timeline.getDocument();Math.min(a,c.event.highlightColors.length-1);a=d.createElement("div");a.style.position="absolute";a.style.overflow="hidden";a.style.left=b.left-2+"px";a.style.width=b.width+4+"px";a.style.top=b.top-2+"px";a.style.height=b.height+4+"px";this._highlightLayer.appendChild(a)}};
Timeline.CompactEventPainter.prototype._onClickMultiplePreciseInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),c);a=[];for(d=0;d<c.length;d++)a.push(c[d].getID());this._fireOnSelect(a);b.cancelBubble=!0;SimileAjax.DOM.cancelEvent(b);return!1};
Timeline.CompactEventPainter.prototype._onClickInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=!0;SimileAjax.DOM.cancelEvent(b);return!1};
Timeline.CompactEventPainter.prototype._onClickDurationEvent=function(a,b,c){if("pageX"in b)var a=b.pageX,d=b.pageY;else d=SimileAjax.DOM.getPageCoordinates(a),a=b.offsetX+d.left,d=b.offsetY+d.top;this._showBubble(a,d,[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=!0;SimileAjax.DOM.cancelEvent(b);return!1};
Timeline.CompactEventPainter.prototype.showBubble=function(a){var b=this._eventIdToElmt[a.getID()];if(b){var c=SimileAjax.DOM.getPageCoordinates(b);this._showBubble(c.left+b.offsetWidth/2,c.top+b.offsetHeight/2,[a])}};
Timeline.CompactEventPainter.prototype._showBubble=function(a,b,c){var d=document.createElement("div"),c="fillInfoBubble"in c?[c]:c,h=0;for(;h<c.length;h++){var g=document.createElement("div");d.appendChild(g);c[h].fillInfoBubble(g,this._params.theme,this._band.getLabeller())}SimileAjax.WindowManager.cancelPopups();SimileAjax.Graphics.createBubbleForContentAndPoint(d,a,b,this._params.theme.event.bubble.width)};Timeline.CompactEventPainter.prototype._fireOnSelect=function(a){for(var b=0;b<this._onSelectListeners.length;b++)this._onSelectListeners[b](a)};
