Timeline.DetailedEventPainter=function(b){this._params=b;this._onSelectListeners=[];this._frc=this._highlightMatcher=this._filterMatcher=null;this._eventIdToElmt={}};Timeline.DetailedEventPainter.prototype.initialize=function(b,a){this._band=b;this._timeline=a;this._eventIdToElmt=this._highlightLayer=this._lineLayer=this._eventLayer=this._backLayer=null};Timeline.DetailedEventPainter.prototype.getType=function(){return"detailed"};Timeline.DetailedEventPainter.prototype.addOnSelectListener=function(b){this._onSelectListeners.push(b)};
Timeline.DetailedEventPainter.prototype.removeOnSelectListener=function(b){for(var a=0;a<this._onSelectListeners.length;a++)if(this._onSelectListeners[a]==b){this._onSelectListeners.splice(a,1);break}};Timeline.DetailedEventPainter.prototype.getFilterMatcher=function(){return this._filterMatcher};Timeline.DetailedEventPainter.prototype.setFilterMatcher=function(b){this._filterMatcher=b};Timeline.DetailedEventPainter.prototype.getHighlightMatcher=function(){return this._highlightMatcher};
Timeline.DetailedEventPainter.prototype.setHighlightMatcher=function(b){this._highlightMatcher=b};
Timeline.DetailedEventPainter.prototype.paint=function(){var b=this._band.getEventSource();if(b!=null){this._eventIdToElmt={};this._prepareForPainting();for(var a=this._params.theme.event,c=Math.max(a.track.height,this._frc.getLineHeight()),a={trackOffset:Math.round(this._band.getViewWidth()/2-c/2),trackHeight:c,trackGap:a.track.gap,trackIncrement:c+a.track.gap,icon:a.instant.icon,iconWidth:a.instant.iconWidth,iconHeight:a.instant.iconHeight,labelWidth:a.label.width},d=this._band.getMinDate(),f=this._band.getMaxDate(),
c=this._filterMatcher!=null?this._filterMatcher:function(){return!0},h=this._highlightMatcher!=null?this._highlightMatcher:function(){return-1},b=b.getEventReverseIterator(d,f);b.hasNext();)d=b.next(),c(d)&&this.paintEvent(d,a,this._params.theme,h(d));this._highlightLayer.style.display="block";this._lineLayer.style.display="block";this._eventLayer.style.display="block";this._band.updateEventTrackInfo(this._lowerTracks.length+this._upperTracks.length,a.trackIncrement)}};
Timeline.DetailedEventPainter.prototype.softPaint=function(){};
Timeline.DetailedEventPainter.prototype._prepareForPainting=function(){var b=this._band;if(this._backLayer==null){this._backLayer=this._band.createLayerDiv(0,"timeline-band-events");this._backLayer.style.visibility="hidden";var a=document.createElement("span");a.className="timeline-event-label";this._backLayer.appendChild(a);this._frc=SimileAjax.Graphics.getFontRenderingContext(a)}this._frc.update();this._lowerTracks=[];this._upperTracks=[];this._highlightLayer!=null&&b.removeLayerDiv(this._highlightLayer);
this._highlightLayer=b.createLayerDiv(105,"timeline-band-highlights");this._highlightLayer.style.display="none";this._lineLayer!=null&&b.removeLayerDiv(this._lineLayer);this._lineLayer=b.createLayerDiv(110,"timeline-band-lines");this._lineLayer.style.display="none";this._eventLayer!=null&&b.removeLayerDiv(this._eventLayer);this._eventLayer=b.createLayerDiv(110,"timeline-band-events");this._eventLayer.style.display="none"};
Timeline.DetailedEventPainter.prototype.paintEvent=function(b,a,c,d){b.isInstant()?this.paintInstantEvent(b,a,c,d):this.paintDurationEvent(b,a,c,d)};Timeline.DetailedEventPainter.prototype.paintInstantEvent=function(b,a,c,d){b.isImprecise()?this.paintImpreciseInstantEvent(b,a,c,d):this.paintPreciseInstantEvent(b,a,c,d)};Timeline.DetailedEventPainter.prototype.paintDurationEvent=function(b,a,c,d){b.isImprecise()?this.paintImpreciseDurationEvent(b,a,c,d):this.paintPreciseDurationEvent(b,a,c,d)};
Timeline.DetailedEventPainter.prototype.paintPreciseInstantEvent=function(b,a,c,d){this._timeline.getDocument();var f=b.getText(),h=b.getStart(),e=Math.round(this._band.dateToPixelOffset(h)),g=Math.round(e+a.iconWidth/2),i=Math.round(e-a.iconWidth/2),h=this._frc.computeSize(f),j=this._findFreeTrackForSolid(g,e),l=this._paintEventIcon(b,j,i,a,c);g+=c.event.label.offsetFromLine;var k=j,m=this._getTrackData(j);Math.min(m.solid,m.text)>=g+h.width?(m.solid=i,m.text=g):(m.solid=i,g=e+c.event.label.offsetFromLine,
k=this._findFreeTrackForText(j,g+h.width,function(a){a.line=e-2}),this._getTrackData(k).text=i,this._paintEventLine(b,e,j,k,a,c));var a=Math.round(a.trackOffset+k*a.trackIncrement+a.trackHeight/2-h.height/2),f=this._paintEventLabel(b,f,g,a,h.width,h.height,c),n=this,a=function(a,c){return n._onClickInstantEvent(l.elmt,c,b)};SimileAjax.DOM.registerEvent(l.elmt,"mousedown",a);SimileAjax.DOM.registerEvent(f.elmt,"mousedown",a);this._createHighlightDiv(d,l,c);this._eventIdToElmt[b.getID()]=l.elmt};
Timeline.DetailedEventPainter.prototype.paintImpreciseInstantEvent=function(b,a,c,d){this._timeline.getDocument();var f=b.getText(),h=b.getStart(),e=b.getEnd(),g=Math.round(this._band.dateToPixelOffset(h)),i=Math.round(this._band.dateToPixelOffset(e)),j=Math.round(g+a.iconWidth/2),l=Math.round(g-a.iconWidth/2),e=this._frc.computeSize(f),k=this._findFreeTrackForSolid(i,g),h=this._paintEventTape(b,k,g,i,c.event.instant.impreciseColor,c.event.instant.impreciseOpacity,a,c),m=this._paintEventIcon(b,k,
l,a,c);this._getTrackData(k).solid=l;j+=c.event.label.offsetFromLine;var n=j+e.width;n<i?i=k:(j=g+c.event.label.offsetFromLine,n=j+e.width,i=this._findFreeTrackForText(k,n,function(a){a.line=g-2}),this._getTrackData(i).text=l,this._paintEventLine(b,g,k,i,a,c));var a=Math.round(a.trackOffset+i*a.trackIncrement+a.trackHeight/2-e.height/2),f=this._paintEventLabel(b,f,j,a,e.width,e.height,c),o=this,a=function(a,c){return o._onClickInstantEvent(m.elmt,c,b)};SimileAjax.DOM.registerEvent(m.elmt,"mousedown",
a);SimileAjax.DOM.registerEvent(h.elmt,"mousedown",a);SimileAjax.DOM.registerEvent(f.elmt,"mousedown",a);this._createHighlightDiv(d,m,c);this._eventIdToElmt[b.getID()]=m.elmt};
Timeline.DetailedEventPainter.prototype.paintPreciseDurationEvent=function(b,a,c,d){this._timeline.getDocument();var f=b.getText(),h=b.getStart(),e=b.getEnd(),g=Math.round(this._band.dateToPixelOffset(h)),i=Math.round(this._band.dateToPixelOffset(e)),h=this._frc.computeSize(f),e=this._findFreeTrackForSolid(i),j=b.getColor(),j=j!=null?j:c.event.duration.color,l=this._paintEventTape(b,e,g,i,j,100,a,c);this._getTrackData(e).solid=g;i=g+c.event.label.offsetFromLine;j=this._findFreeTrackForText(e,i+h.width,
function(a){a.line=g-2});this._getTrackData(j).text=g-2;this._paintEventLine(b,g,e,j,a,c);var a=Math.round(a.trackOffset+j*a.trackIncrement+a.trackHeight/2-h.height/2),f=this._paintEventLabel(b,f,i,a,h.width,h.height,c),k=this,a=function(a,c){return k._onClickDurationEvent(l.elmt,c,b)};SimileAjax.DOM.registerEvent(l.elmt,"mousedown",a);SimileAjax.DOM.registerEvent(f.elmt,"mousedown",a);this._createHighlightDiv(d,l,c);this._eventIdToElmt[b.getID()]=l.elmt};
Timeline.DetailedEventPainter.prototype.paintImpreciseDurationEvent=function(b,a,c,d){this._timeline.getDocument();var f=b.getText(),h=b.getStart(),e=b.getLatestStart(),g=b.getEnd(),i=b.getEarliestEnd(),h=Math.round(this._band.dateToPixelOffset(h)),j=Math.round(this._band.dateToPixelOffset(e)),g=Math.round(this._band.dateToPixelOffset(g)),l=Math.round(this._band.dateToPixelOffset(i)),i=this._frc.computeSize(f),e=this._findFreeTrackForSolid(g),k=b.getColor(),k=k!=null?k:c.event.duration.color;this._paintEventTape(b,
e,h,g,c.event.duration.impreciseColor,c.event.duration.impreciseOpacity,a,c);var m=this._paintEventTape(b,e,j,l,k,100,a,c);this._getTrackData(e).solid=h;h=j+c.event.label.offsetFromLine;g=this._findFreeTrackForText(e,h+i.width,function(a){a.line=j-2});this._getTrackData(g).text=j-2;this._paintEventLine(b,j,e,g,a,c);var a=Math.round(a.trackOffset+g*a.trackIncrement+a.trackHeight/2-i.height/2),f=this._paintEventLabel(b,f,h,a,i.width,i.height,c),n=this,a=function(a,c){return n._onClickDurationEvent(m.elmt,
c,b)};SimileAjax.DOM.registerEvent(m.elmt,"mousedown",a);SimileAjax.DOM.registerEvent(f.elmt,"mousedown",a);this._createHighlightDiv(d,m,c);this._eventIdToElmt[b.getID()]=m.elmt};
Timeline.DetailedEventPainter.prototype._findFreeTrackForSolid=function(b,a){for(var c=0;;c++){if(c<this._lowerTracks.length){var d=this._lowerTracks[c];if(Math.min(d.solid,d.text)>b&&(!a||d.line>a))return c}else return this._lowerTracks.push({solid:Number.POSITIVE_INFINITY,text:Number.POSITIVE_INFINITY,line:Number.POSITIVE_INFINITY}),c;if(c<this._upperTracks.length){if(d=this._upperTracks[c],Math.min(d.solid,d.text)>b&&(!a||d.line>a))return-1-c}else return this._upperTracks.push({solid:Number.POSITIVE_INFINITY,
text:Number.POSITIVE_INFINITY,line:Number.POSITIVE_INFINITY}),-1-c}};
Timeline.DetailedEventPainter.prototype._findFreeTrackForText=function(b,a,c){var d,f;b<0?(d=!0,b=-b,a=this._findFreeUpperTrackForText(b,a),f=-1-a):b>0?(d=!1,b+=1,f=a=this._findFreeLowerTrackForText(b,a)):(f=this._findFreeUpperTrackForText(0,a),a=this._findFreeLowerTrackForText(1,a),a-1<=f?(d=!1,b=1,f=a):(d=!0,b=0,a=f,f=-1-a));if(d){a==this._upperTracks.length&&this._upperTracks.push({solid:Number.POSITIVE_INFINITY,text:Number.POSITIVE_INFINITY,line:Number.POSITIVE_INFINITY});for(d=b;d<a;d++)c(this._upperTracks[d])}else{a==
this._lowerTracks.length&&this._lowerTracks.push({solid:Number.POSITIVE_INFINITY,text:Number.POSITIVE_INFINITY,line:Number.POSITIVE_INFINITY});for(d=b;d<a;d++)c(this._lowerTracks[d])}return f};Timeline.DetailedEventPainter.prototype._findFreeLowerTrackForText=function(b,a){for(;b<this._lowerTracks.length;b++){var c=this._lowerTracks[b];if(Math.min(c.solid,c.text)>=a)break}return b};
Timeline.DetailedEventPainter.prototype._findFreeUpperTrackForText=function(b,a){for(;b<this._upperTracks.length;b++){var c=this._upperTracks[b];if(Math.min(c.solid,c.text)>=a)break}return b};Timeline.DetailedEventPainter.prototype._getTrackData=function(b){return b<0?this._upperTracks[-b-1]:this._lowerTracks[b]};
Timeline.DetailedEventPainter.prototype._paintEventLine=function(b,a,c,d,f,h){var b=Math.round(f.trackOffset+c*f.trackIncrement+f.trackHeight/2),f=Math.round(Math.abs(d-c)*f.trackIncrement),e="1px solid "+h.event.label.lineColor,g=this._timeline.getDocument().createElement("div");g.style.position="absolute";g.style.left=a+"px";g.style.width=h.event.label.offsetFromLine+"px";g.style.height=f+"px";c>d?(g.style.top=b-f+"px",g.style.borderTop=e):(g.style.top=b+"px",g.style.borderBottom=e);g.style.borderLeft=
e;this._lineLayer.appendChild(g)};
Timeline.DetailedEventPainter.prototype._paintEventIcon=function(b,a,c,d){var f=b.getIcon(),f=f!=null?f:d.icon,a=Math.round(d.trackOffset+a*d.trackIncrement+d.trackHeight/2-d.iconHeight/2),f=SimileAjax.Graphics.createTranslucentImage(f),h=this._timeline.getDocument().createElement("div");h.style.position="absolute";h.style.left=c+"px";h.style.top=a+"px";h.appendChild(f);h.style.cursor="pointer";if(b._title!=null)h.title=b._title;this._eventLayer.appendChild(h);return{left:c,top:a,width:d.iconWidth,
height:d.iconHeight,elmt:h}};
Timeline.DetailedEventPainter.prototype._paintEventLabel=function(b,a,c,d,f,h,e){var g=this._timeline.getDocument(),i=g.createElement("div");i.style.position="absolute";i.style.left=c+"px";i.style.width=f+"px";i.style.top=d+"px";i.style.height=h+"px";i.style.backgroundColor=e.event.label.backgroundColor;SimileAjax.Graphics.setOpacity(i,e.event.label.backgroundOpacity);this._eventLayer.appendChild(i);e=g.createElement("div");e.style.position="absolute";e.style.left=c+"px";e.style.width=f+"px";e.style.top=
d+"px";e.innerHTML=a;e.style.cursor="pointer";if(b._title!=null)e.title=b._title;a=b.getTextColor();a==null&&(a=b.getColor());if(a!=null)e.style.color=a;this._eventLayer.appendChild(e);return{left:c,top:d,width:f,height:h,elmt:e}};
Timeline.DetailedEventPainter.prototype._paintEventTape=function(b,a,c,d,f,h,e,g){d-=c;g=g.event.tape.height;a=Math.round(e.trackOffset+a*e.trackIncrement+e.trackHeight/2-g/2);e=this._timeline.getDocument().createElement("div");e.style.position="absolute";e.style.left=c+"px";e.style.width=d+"px";e.style.top=a+"px";e.style.height=g+"px";e.style.backgroundColor=f;e.style.overflow="hidden";e.style.cursor="pointer";if(b._title!=null)e.title=b._title;SimileAjax.Graphics.setOpacity(e,h);this._eventLayer.appendChild(e);
return{left:c,top:a,width:d,height:g,elmt:e}};Timeline.DetailedEventPainter.prototype._createHighlightDiv=function(b,a,c){if(b>=0){var d=this._timeline.getDocument(),c=c.event,b=c.highlightColors[Math.min(b,c.highlightColors.length-1)],d=d.createElement("div");d.style.position="absolute";d.style.overflow="hidden";d.style.left=a.left-2+"px";d.style.width=a.width+4+"px";d.style.top=a.top-2+"px";d.style.height=a.height+4+"px";d.style.background=b;this._highlightLayer.appendChild(d)}};
Timeline.DetailedEventPainter.prototype._onClickInstantEvent=function(b,a,c){var d=SimileAjax.DOM.getPageCoordinates(b);this._showBubble(d.left+Math.ceil(b.offsetWidth/2),d.top+Math.ceil(b.offsetHeight/2),c);this._fireOnSelect(c.getID());a.cancelBubble=!0;SimileAjax.DOM.cancelEvent(a);return!1};
Timeline.DetailedEventPainter.prototype._onClickDurationEvent=function(b,a,c){if("pageX"in a)var b=a.pageX,d=a.pageY;else d=SimileAjax.DOM.getPageCoordinates(b),b=a.offsetX+d.left,d=a.offsetY+d.top;this._showBubble(b,d,c);this._fireOnSelect(c.getID());a.cancelBubble=!0;SimileAjax.DOM.cancelEvent(a);return!1};
Timeline.DetailedEventPainter.prototype.showBubble=function(b){var a=this._eventIdToElmt[b.getID()];if(a){var c=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(c.left+a.offsetWidth/2,c.top+a.offsetHeight/2,b)}};
Timeline.DetailedEventPainter.prototype._showBubble=function(b,a,c){var d=document.createElement("div"),f=this._params.theme.event.bubble;c.fillInfoBubble(d,this._params.theme,this._band.getLabeller());SimileAjax.WindowManager.cancelPopups();SimileAjax.Graphics.createBubbleForContentAndPoint(d,b,a,f.width,null,f.maxHeight)};Timeline.DetailedEventPainter.prototype._fireOnSelect=function(b){for(var a=0;a<this._onSelectListeners.length;a++)this._onSelectListeners[a](b)};
