Timeline.LinearEther=function(a){this._params=a;this._interval=a.interval;this._pixelsPerInterval=a.pixelsPerInterval};
Timeline.LinearEther.prototype.initialize=function(a,c){this._band=a;this._timeline=c;this._unit=c.getUnit();"startsOn"in this._params?this._start=this._unit.parseFromObject(this._params.startsOn):"endsOn"in this._params?(this._start=this._unit.parseFromObject(this._params.endsOn),this.shiftPixels(-this._timeline.getPixelLength())):(this._start="centersOn"in this._params?this._unit.parseFromObject(this._params.centersOn):this._unit.makeDefaultValue(),this.shiftPixels(-this._timeline.getPixelLength()/
2))};Timeline.LinearEther.prototype.setDate=function(a){this._start=this._unit.cloneValue(a)};Timeline.LinearEther.prototype.shiftPixels=function(a){this._start=this._unit.change(this._start,this._interval*a/this._pixelsPerInterval)};Timeline.LinearEther.prototype.dateToPixelOffset=function(a){return this._pixelsPerInterval*this._unit.compare(a,this._start)/this._interval};Timeline.LinearEther.prototype.pixelOffsetToDate=function(a){return this._unit.change(this._start,a*this._interval/this._pixelsPerInterval)};
Timeline.LinearEther.prototype.zoom=function(a){var c=0,e=c=this._band._zoomIndex;a&&c>0&&(e=c-1);!a&&c<this._band._zoomSteps.length-1&&(e=c+1);this._band._zoomIndex=e;this._interval=SimileAjax.DateTime.gregorianUnitLengths[this._band._zoomSteps[e].unit];this._pixelsPerInterval=this._band._zoomSteps[e].pixelsPerInterval;return c=this._band._zoomSteps[e].unit-this._band._zoomSteps[c].unit};
Timeline.HotZoneEther=function(a){this._params=a;this._interval=a.interval;this._pixelsPerInterval=a.pixelsPerInterval;this._theme=a.theme};
Timeline.HotZoneEther.prototype.initialize=function(a,c){this._band=a;this._timeline=c;this._unit=c.getUnit();this._zones=[{startTime:Number.NEGATIVE_INFINITY,endTime:Number.POSITIVE_INFINITY,magnify:1}];for(var e=this._params,d=0;d<e.zones.length;d++)for(var f=e.zones[d],b=this._unit.parseFromObject(f.start),h=this._unit.parseFromObject(f.end),g=0;g<this._zones.length&&this._unit.compare(h,b)>0;g++){var i=this._zones[g];if(this._unit.compare(b,i.endTime)<0){if(this._unit.compare(b,i.startTime)>0)this._zones.splice(g,
0,{startTime:i.startTime,endTime:b,magnify:i.magnify}),g++,i.startTime=b;this._unit.compare(h,i.endTime)<0?(this._zones.splice(g,0,{startTime:b,endTime:h,magnify:f.magnify*i.magnify}),g++,b=i.startTime=h):(i.magnify*=f.magnify,b=i.endTime)}}"startsOn"in this._params?this._start=this._unit.parseFromObject(this._params.startsOn):"endsOn"in this._params?(this._start=this._unit.parseFromObject(this._params.endsOn),this.shiftPixels(-this._timeline.getPixelLength())):(this._start="centersOn"in this._params?
this._unit.parseFromObject(this._params.centersOn):this._unit.makeDefaultValue(),this.shiftPixels(-this._timeline.getPixelLength()/2))};Timeline.HotZoneEther.prototype.setDate=function(a){this._start=this._unit.cloneValue(a)};Timeline.HotZoneEther.prototype.shiftPixels=function(a){this._start=this.pixelOffsetToDate(a)};Timeline.HotZoneEther.prototype.dateToPixelOffset=function(a){return this._dateDiffToPixelOffset(this._start,a)};
Timeline.HotZoneEther.prototype.pixelOffsetToDate=function(a){return this._pixelOffsetToDate(a,this._start)};Timeline.HotZoneEther.prototype.zoom=function(a){var c=0,e=c=this._band._zoomIndex;a&&c>0&&(e=c-1);!a&&c<this._band._zoomSteps.length-1&&(e=c+1);this._band._zoomIndex=e;this._interval=SimileAjax.DateTime.gregorianUnitLengths[this._band._zoomSteps[e].unit];this._pixelsPerInterval=this._band._zoomSteps[e].pixelsPerInterval;return c=this._band._zoomSteps[e].unit-this._band._zoomSteps[c].unit};
Timeline.HotZoneEther.prototype._dateDiffToPixelOffset=function(a,c){var e=this._getScale(),d=a,f=0;if(this._unit.compare(d,c)<0){for(var b=0;b<this._zones.length;){if(this._unit.compare(d,this._zones[b].endTime)<0)break;b++}for(;this._unit.compare(d,c)<0;){var h=this._zones[b],g=this._unit.earlier(c,h.endTime);f+=this._unit.compare(g,d)/(e/h.magnify);d=g;b++}}else{for(b=this._zones.length-1;b>=0;){if(this._unit.compare(d,this._zones[b].startTime)>0)break;b--}for(;this._unit.compare(d,c)>0;)h=this._zones[b],
g=this._unit.later(c,h.startTime),f+=this._unit.compare(g,d)/(e/h.magnify),d=g,b--}return f};
Timeline.HotZoneEther.prototype._pixelOffsetToDate=function(a,c){var e=this._getScale(),d=c;if(a>0){for(var f=0;f<this._zones.length;){if(this._unit.compare(d,this._zones[f].endTime)<0)break;f++}for(;a>0;){var b=this._zones[f],h=e/b.magnify;if(b.endTime==Number.POSITIVE_INFINITY)d=this._unit.change(d,a*h),a=0;else{var g=this._unit.compare(b.endTime,d)/h;g>a?(d=this._unit.change(d,a*h),a=0):(d=b.endTime,a-=g)}f++}}else{for(f=this._zones.length-1;f>=0;){if(this._unit.compare(d,this._zones[f].startTime)>
0)break;f--}for(a=-a;a>0;)b=this._zones[f],h=e/b.magnify,b.startTime==Number.NEGATIVE_INFINITY?(d=this._unit.change(d,-a*h),a=0):(g=this._unit.compare(d,b.startTime)/h,g>a?(d=this._unit.change(d,-a*h),a=0):(d=b.startTime,a-=g)),f--}return d};Timeline.HotZoneEther.prototype._getScale=function(){return this._interval/this._pixelsPerInterval};
