Timeline.OriginalEventPainter=function(a){this._params=a;this._onSelectListeners=[];this._eventPaintListeners=[];this._frc=this._highlightMatcher=this._filterMatcher=null;this._eventIdToElmt={}};Timeline.OriginalEventPainter.prototype.initialize=function(a,b){this._band=a;this._timeline=b;this._eventIdToElmt=this._highlightLayer=this._lineLayer=this._eventLayer=this._backLayer=null};Timeline.OriginalEventPainter.prototype.getType=function(){return"original"};
Timeline.OriginalEventPainter.prototype.addOnSelectListener=function(a){this._onSelectListeners.push(a)};Timeline.OriginalEventPainter.prototype.removeOnSelectListener=function(a){for(var b=0;b<this._onSelectListeners.length;b++)if(this._onSelectListeners[b]==a){this._onSelectListeners.splice(b,1);break}};Timeline.OriginalEventPainter.prototype.addEventPaintListener=function(a){this._eventPaintListeners.push(a)};
Timeline.OriginalEventPainter.prototype.removeEventPaintListener=function(a){for(var b=0;b<this._eventPaintListeners.length;b++)if(this._eventPaintListeners[b]==a){this._eventPaintListeners.splice(b,1);break}};Timeline.OriginalEventPainter.prototype.getFilterMatcher=function(){return this._filterMatcher};Timeline.OriginalEventPainter.prototype.setFilterMatcher=function(a){this._filterMatcher=a};Timeline.OriginalEventPainter.prototype.getHighlightMatcher=function(){return this._highlightMatcher};
Timeline.OriginalEventPainter.prototype.setHighlightMatcher=function(a){this._highlightMatcher=a};
Timeline.OriginalEventPainter.prototype.paint=function(){var a=this._band.getEventSource();if(a!=null){this._eventIdToElmt={};this._fireEventPaintListeners("paintStarting",null,null);this._prepareForPainting();for(var b=this._params.theme.event,c=Math.max(b.track.height,b.tape.height+this._frc.getLineHeight()),b={trackOffset:b.track.offset,trackHeight:c,trackGap:b.track.gap,trackIncrement:c+b.track.gap,icon:b.instant.icon,iconWidth:b.instant.iconWidth,iconHeight:b.instant.iconHeight,labelWidth:b.label.width,
maxLabelChar:b.label.maxLabelChar,impreciseIconMargin:b.instant.impreciseIconMargin},d=this._band.getMinDate(),e=this._band.getMaxDate(),c=this._filterMatcher!=null?this._filterMatcher:function(){return!0},g=this._highlightMatcher!=null?this._highlightMatcher:function(){return-1},a=a.getEventReverseIterator(d,e);a.hasNext();)d=a.next(),c(d)&&this.paintEvent(d,b,this._params.theme,g(d));this._highlightLayer.style.display="block";this._lineLayer.style.display="block";this._eventLayer.style.display=
"block";this._band.updateEventTrackInfo(this._tracks.length,b.trackIncrement);this._fireEventPaintListeners("paintEnded",null,null)}};Timeline.OriginalEventPainter.prototype.softPaint=function(){};
Timeline.OriginalEventPainter.prototype._prepareForPainting=function(){var a=this._band;if(this._backLayer==null){this._backLayer=this._band.createLayerDiv(0,"timeline-band-events");this._backLayer.style.visibility="hidden";var b=document.createElement("span");b.className="timeline-event-label";this._backLayer.appendChild(b);this._frc=SimileAjax.Graphics.getFontRenderingContext(b)}this._frc.update();this._tracks=[];this._highlightLayer!=null&&a.removeLayerDiv(this._highlightLayer);this._highlightLayer=
a.createLayerDiv(105,"timeline-band-highlights");this._highlightLayer.style.display="none";this._lineLayer!=null&&a.removeLayerDiv(this._lineLayer);this._lineLayer=a.createLayerDiv(110,"timeline-band-lines");this._lineLayer.style.display="none";this._eventLayer!=null&&a.removeLayerDiv(this._eventLayer);this._eventLayer=a.createLayerDiv(115,"timeline-band-events");this._eventLayer.style.display="none"};
Timeline.OriginalEventPainter.prototype.paintEvent=function(a,b,c,d){a.isInstant()?this.paintInstantEvent(a,b,c,d):this.paintDurationEvent(a,b,c,d)};Timeline.OriginalEventPainter.prototype.paintInstantEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseInstantEvent(a,b,c,d):this.paintPreciseInstantEvent(a,b,c,d)};Timeline.OriginalEventPainter.prototype.paintDurationEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseDurationEvent(a,b,c,d):this.paintPreciseDurationEvent(a,b,c,d)};
Timeline.OriginalEventPainter.prototype.paintPreciseInstantEvent=function(a,b,c,d){this._timeline.getDocument();var e=a.getText(),g=a.getStart(),g=Math.round(this._band.dateToPixelOffset(g)),f=Math.round(g+b.iconWidth/2),g=Math.round(g-b.iconWidth/2),h=this._getLabelDivClassName(a),i=this._frc.computeSize(e,h),j=f+c.event.label.offsetFromLine,f=this._findFreeTrack(a,j+i.width),n=Math.round(b.trackOffset+f*b.trackIncrement+b.trackHeight/2-i.height/2),k=this._paintEventIcon(a,f,g,b,c,0),e=this._paintEventLabel(a,
e,j,n,i.width,i.height,c,h,d),b=[k.elmt,e.elmt],l=this,h=function(b,c){return l._onClickInstantEvent(k.elmt,c,a)};SimileAjax.DOM.registerEvent(k.elmt,"mousedown",h);SimileAjax.DOM.registerEvent(e.elmt,"mousedown",h);c=this._createHighlightDiv(d,k,c,a);c!=null&&b.push(c);this._fireEventPaintListeners("paintedEvent",a,b);this._eventIdToElmt[a.getID()]=k.elmt;this._tracks[f]=g};
Timeline.OriginalEventPainter.prototype.paintImpreciseInstantEvent=function(a,b,c,d){this._timeline.getDocument();var e=a.getText(),g=a.getStart(),f=a.getEnd(),h=Math.round(this._band.dateToPixelOffset(g)),i=Math.round(this._band.dateToPixelOffset(f)),g=Math.round(h+b.iconWidth/2),f=Math.round(h-b.iconWidth/2),j=this._getLabelDivClassName(a),n=this._frc.computeSize(e,j),k=g+c.event.label.offsetFromLine,g=Math.max(k+n.width,i),g=this._findFreeTrack(a,g),l=c.event.tape.height,o=Math.round(b.trackOffset+
g*b.trackIncrement+l),m=this._paintEventIcon(a,g,f,b,c,l),e=this._paintEventLabel(a,e,k,o,n.width,n.height,c,j,d),j=a.getColor(),j=j!=null?j:c.event.instant.impreciseColor,h=this._paintEventTape(a,g,h,i,j,c.event.instant.impreciseOpacity,b,c,0),b=[m.elmt,e.elmt,h.elmt],p=this,i=function(b,c){return p._onClickInstantEvent(m.elmt,c,a)};SimileAjax.DOM.registerEvent(m.elmt,"mousedown",i);SimileAjax.DOM.registerEvent(h.elmt,"mousedown",i);SimileAjax.DOM.registerEvent(e.elmt,"mousedown",i);c=this._createHighlightDiv(d,
m,c,a);c!=null&&b.push(c);this._fireEventPaintListeners("paintedEvent",a,b);this._eventIdToElmt[a.getID()]=m.elmt;this._tracks[g]=f};
Timeline.OriginalEventPainter.prototype.paintPreciseDurationEvent=function(a,b,c,d){this._timeline.getDocument();var e=a.getText(),g=a.getStart(),f=a.getEnd(),g=Math.round(this._band.dateToPixelOffset(g)),h=Math.round(this._band.dateToPixelOffset(f)),i=this._getLabelDivClassName(a),j=this._frc.computeSize(e,i),f=Math.max(g+j.width,h),f=this._findFreeTrack(a,f),n=Math.round(b.trackOffset+f*b.trackIncrement+c.event.tape.height),k=a.getColor(),k=k!=null?k:c.event.duration.color,l=this._paintEventTape(a,
f,g,h,k,100,b,c,0),e=this._paintEventLabel(a,e,g,n,j.width,j.height,c,i,d),b=[l.elmt,e.elmt],o=this,h=function(b,c){return o._onClickDurationEvent(l.elmt,c,a)};SimileAjax.DOM.registerEvent(l.elmt,"mousedown",h);SimileAjax.DOM.registerEvent(e.elmt,"mousedown",h);c=this._createHighlightDiv(d,l,c,a);c!=null&&b.push(c);this._fireEventPaintListeners("paintedEvent",a,b);this._eventIdToElmt[a.getID()]=l.elmt;this._tracks[f]=g};
Timeline.OriginalEventPainter.prototype.paintImpreciseDurationEvent=function(a,b,c,d){this._timeline.getDocument();var e=a.getText(),g=a.getStart(),f=a.getLatestStart(),h=a.getEnd(),i=a.getEarliestEnd(),g=Math.round(this._band.dateToPixelOffset(g)),f=Math.round(this._band.dateToPixelOffset(f)),h=Math.round(this._band.dateToPixelOffset(h)),j=Math.round(this._band.dateToPixelOffset(i)),n=this._getLabelDivClassName(a),k=this._frc.computeSize(e,n),i=Math.max(f+k.width,h),i=this._findFreeTrack(a,i),l=
Math.round(b.trackOffset+i*b.trackIncrement+c.event.tape.height),o=a.getColor(),o=o!=null?o:c.event.duration.color,h=this._paintEventTape(a,i,g,h,c.event.duration.impreciseColor,c.event.duration.impreciseOpacity,b,c,0),m=this._paintEventTape(a,i,f,j,o,100,b,c,1),b=this._paintEventLabel(a,e,f,l,k.width,k.height,c,n,d),e=[h.elmt,m.elmt,b.elmt],p=this,f=function(b,c){return p._onClickDurationEvent(m.elmt,c,a)};SimileAjax.DOM.registerEvent(m.elmt,"mousedown",f);SimileAjax.DOM.registerEvent(b.elmt,"mousedown",
f);c=this._createHighlightDiv(d,m,c,a);c!=null&&e.push(c);this._fireEventPaintListeners("paintedEvent",a,e);this._eventIdToElmt[a.getID()]=m.elmt;this._tracks[i]=g};Timeline.OriginalEventPainter.prototype._encodeEventElID=function(a,b){return Timeline.EventUtils.encodeEventElID(this._timeline,this._band,a,b)};Timeline.OriginalEventPainter.prototype._findFreeTrack=function(a,b){var c=a.getTrackNum();if(c!=null)return c;for(c=0;c<this._tracks.length;c++)if(this._tracks[c]>b)break;return c};
Timeline.OriginalEventPainter.prototype._paintEventIcon=function(a,b,c,d,e,g){e=a.getIcon();e=e!=null?e:d.icon;b=g>0?d.trackOffset+b*d.trackIncrement+g+d.impreciseIconMargin:Math.round(d.trackOffset+b*d.trackIncrement+d.trackHeight/2-d.iconHeight/2);g=SimileAjax.Graphics.createTranslucentImage(e);e=this._timeline.getDocument().createElement("div");e.className=this._getElClassName("timeline-event-icon",a,"icon");e.id=this._encodeEventElID("icon",a);e.style.left=c+"px";e.style.top=b+"px";e.appendChild(g);
if(a._title!=null)e.title=a._title;this._eventLayer.appendChild(e);return{left:c,top:b,width:d.iconWidth,height:d.iconHeight,elmt:e}};
Timeline.OriginalEventPainter.prototype._paintEventLabel=function(a,b,c,d,e,g,f,h,i){var j=this._timeline.getDocument().createElement("div");j.className=h;j.id=this._encodeEventElID("label",a);j.style.left=c+"px";j.style.width=e+"px";j.style.top=d+"px";j.innerHTML=b;if(a._title!=null)j.title=a._title;b=a.getTextColor();b==null&&(b=a.getColor());if(b!=null)j.style.color=b;if(f.event.highlightLabelBackground&&i>=0)j.style.background=this._getHighlightColor(i,f);this._eventLayer.appendChild(j);return{left:c,
top:d,width:e,height:g,elmt:j}};
Timeline.OriginalEventPainter.prototype._paintEventTape=function(a,b,c,d,e,g,f,h,i){d-=c;h=h.event.tape.height;b=f.trackOffset+b*f.trackIncrement;f=this._timeline.getDocument().createElement("div");f.className=this._getElClassName("timeline-event-tape",a,"tape");f.id=this._encodeEventElID("tape"+i,a);f.style.left=c+"px";f.style.width=d+"px";f.style.height=h+"px";f.style.top=b+"px";if(a._title!=null)f.title=a._title;if(e!=null)f.style.backgroundColor=e;e=a.getTapeImage();a=a.getTapeRepeat();a=a!=null?
a:"repeat";if(e!=null)f.style.backgroundImage="url("+e+")",f.style.backgroundRepeat=a;SimileAjax.Graphics.setOpacity(f,g);this._eventLayer.appendChild(f);return{left:c,top:b,width:d,height:h,elmt:f}};Timeline.OriginalEventPainter.prototype._getLabelDivClassName=function(a){return this._getElClassName("timeline-event-label",a,"label")};Timeline.OriginalEventPainter.prototype._getElClassName=function(a,b,c){var b=b.getClassName(),d=[];b&&(c&&d.push(c+"-"+b+" "),d.push(b+" "));d.push(a);return d.join("")};
Timeline.OriginalEventPainter.prototype._getHighlightColor=function(a,b){var c=b.event.highlightColors;return c[Math.min(a,c.length-1)]};
Timeline.OriginalEventPainter.prototype._createHighlightDiv=function(a,b,c,d){var e=null;if(a>=0)e=this._timeline.getDocument(),a=this._getHighlightColor(a,c),e=e.createElement("div"),e.className=this._getElClassName("timeline-event-highlight",d,"highlight"),e.id=this._encodeEventElID("highlight0",d),e.style.position="absolute",e.style.overflow="hidden",e.style.left=b.left-2+"px",e.style.width=b.width+4+"px",e.style.top=b.top-2+"px",e.style.height=b.height+4+"px",e.style.background=a,this._highlightLayer.appendChild(e);
return e};Timeline.OriginalEventPainter.prototype._onClickInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),c);this._fireOnSelect(c.getID());b.cancelBubble=!0;SimileAjax.DOM.cancelEvent(b);return!1};
Timeline.OriginalEventPainter.prototype._onClickDurationEvent=function(a,b,c){if("pageX"in b)var a=b.pageX,d=b.pageY;else d=SimileAjax.DOM.getPageCoordinates(a),a=b.offsetX+d.left,d=b.offsetY+d.top;this._showBubble(a,d,c);this._fireOnSelect(c.getID());b.cancelBubble=!0;SimileAjax.DOM.cancelEvent(b);return!1};
Timeline.OriginalEventPainter.prototype.showBubble=function(a){var b=this._eventIdToElmt[a.getID()];if(b){var c=SimileAjax.DOM.getPageCoordinates(b);this._showBubble(c.left+b.offsetWidth/2,c.top+b.offsetHeight/2,a)}};
Timeline.OriginalEventPainter.prototype._showBubble=function(a,b,c){var d=document.createElement("div"),e=this._params.theme.event.bubble;c.fillInfoBubble(d,this._params.theme,this._band.getLabeller());SimileAjax.WindowManager.cancelPopups();SimileAjax.Graphics.createBubbleForContentAndPoint(d,a,b,e.width,null,e.maxHeight)};Timeline.OriginalEventPainter.prototype._fireOnSelect=function(a){for(var b=0;b<this._onSelectListeners.length;b++)this._onSelectListeners[b](a)};
Timeline.OriginalEventPainter.prototype._fireEventPaintListeners=function(a,b,c){for(var d=0;d<this._eventPaintListeners.length;d++)this._eventPaintListeners[d](this._band,a,b,c)};
