Timeline.DefaultEventSource=function(a){this._events=a instanceof Object?a:new SimileAjax.EventIndex;this._listeners=[]};Timeline.DefaultEventSource.prototype.addListener=function(a){this._listeners.push(a)};Timeline.DefaultEventSource.prototype.removeListener=function(a){for(var b=0;b<this._listeners.length;b++)if(this._listeners[b]==a){this._listeners.splice(b,1);break}};
Timeline.DefaultEventSource.prototype.loadXML=function(a,b){for(var f=this._getBaseURL(b),e=a.documentElement.getAttribute("wiki-url"),g=a.documentElement.getAttribute("wiki-section"),i=a.documentElement.getAttribute("date-time-format"),i=this._events.getUnit().getParser(i),d=a.documentElement.firstChild,c=!1;d!=null;){if(d.nodeType==1){c="";if(d.firstChild!=null&&d.firstChild.nodeType==3)c=d.firstChild.nodeValue;var h=d.getAttribute("isDuration")===null&&d.getAttribute("durationEvent")===null||d.getAttribute("isDuration")==
"false"||d.getAttribute("durationEvent")=="false",c=new Timeline.DefaultEventSource.Event({id:d.getAttribute("id"),start:i(d.getAttribute("start")),end:i(d.getAttribute("end")),latestStart:i(d.getAttribute("latestStart")),earliestEnd:i(d.getAttribute("earliestEnd")),instant:h,text:d.getAttribute("title"),description:c,image:this._resolveRelativeURL(d.getAttribute("image"),f),link:this._resolveRelativeURL(d.getAttribute("link"),f),icon:this._resolveRelativeURL(d.getAttribute("icon"),f),color:d.getAttribute("color"),
textColor:d.getAttribute("textColor"),hoverText:d.getAttribute("hoverText"),classname:d.getAttribute("classname"),tapeImage:d.getAttribute("tapeImage"),tapeRepeat:d.getAttribute("tapeRepeat"),caption:d.getAttribute("caption"),eventID:d.getAttribute("eventID"),trackNum:d.getAttribute("trackNum")});c._node=d;c.getProperty=function(a){return this._node.getAttribute(a)};c.setWikiInfo(e,g);this._events.add(c);c=!0}d=d.nextSibling}c&&this._fire("onAddMany",[])};
Timeline.DefaultEventSource.prototype.loadJSON=function(a,b){var f=this._getBaseURL(b),e=!1;if(a&&a.events){var g="wikiURL"in a?a.wikiURL:null,i="wikiSection"in a?a.wikiSection:null,d="dateTimeFormat"in a?a.dateTimeFormat:null,d=this._events.getUnit().getParser(d),c=0;for(;c<a.events.length;c++){var e=a.events[c],h=e.isDuration||e.durationEvent!=null&&!e.durationEvent,h=new Timeline.DefaultEventSource.Event({id:"id"in e?e.id:void 0,start:d(e.start),end:d(e.end),latestStart:d(e.latestStart),earliestEnd:d(e.earliestEnd),
instant:h,text:e.title,description:e.description,image:this._resolveRelativeURL(e.image,f),link:this._resolveRelativeURL(e.link,f),icon:this._resolveRelativeURL(e.icon,f),color:e.color,textColor:e.textColor,hoverText:e.hoverText,classname:e.classname,tapeImage:e.tapeImage,tapeRepeat:e.tapeRepeat,caption:e.caption,eventID:e.eventID,trackNum:e.trackNum});h._obj=e;h.getProperty=function(a){return this._obj[a]};h.setWikiInfo(g,i);this._events.add(h);e=!0}}e&&this._fire("onAddMany",[])};
Timeline.DefaultEventSource.prototype.loadSPARQL=function(a,b){var f=this._getBaseURL(b),e=this._events.getUnit().getParser("iso8601");if(a!=null){for(var g=a.documentElement.firstChild;g!=null&&(g.nodeType!=1||g.nodeName!="results");)g=g.nextSibling;var i=null,d=null;if(g!=null)i=g.getAttribute("wiki-url"),d=g.getAttribute("wiki-section"),g=g.firstChild;for(var c=!1;g!=null;){if(g.nodeType==1){for(var c={},h=g.firstChild;h!=null;){if(h.nodeType==1&&h.firstChild!=null&&h.firstChild.nodeType==1&&h.firstChild.firstChild!=
null&&h.firstChild.firstChild.nodeType==3)c[h.getAttribute("name")]=h.firstChild.firstChild.nodeValue;h=h.nextSibling}c.start==null&&c.date!=null&&(c.start=c.date);h=c.isDuration===null&&c.durationEvent===null||c.isDuration=="false"||c.durationEvent=="false";h=new Timeline.DefaultEventSource.Event({id:c.id,start:e(c.start),end:e(c.end),latestStart:e(c.latestStart),earliestEnd:e(c.earliestEnd),instant:h,text:c.title,description:c.description,image:this._resolveRelativeURL(c.image,f),link:this._resolveRelativeURL(c.link,
f),icon:this._resolveRelativeURL(c.icon,f),color:c.color,textColor:c.textColor,hoverText:c.hoverText,caption:c.caption,classname:c.classname,tapeImage:c.tapeImage,tapeRepeat:c.tapeRepeat,eventID:c.eventID,trackNum:c.trackNum});h._bindings=c;h.getProperty=function(a){return this._bindings[a]};h.setWikiInfo(i,d);this._events.add(h);c=!0}g=g.nextSibling}c&&this._fire("onAddMany",[])}};Timeline.DefaultEventSource.prototype.add=function(a){this._events.add(a);this._fire("onAddOne",[a])};
Timeline.DefaultEventSource.prototype.addMany=function(a){for(var b=0;b<a.length;b++)this._events.add(a[b]);this._fire("onAddMany",[])};Timeline.DefaultEventSource.prototype.clear=function(){this._events.removeAll();this._fire("onClear",[])};Timeline.DefaultEventSource.prototype.getEvent=function(a){return this._events.getEvent(a)};Timeline.DefaultEventSource.prototype.getEventIterator=function(a,b){return this._events.getIterator(a,b)};
Timeline.DefaultEventSource.prototype.getEventReverseIterator=function(a,b){return this._events.getReverseIterator(a,b)};Timeline.DefaultEventSource.prototype.getAllEventIterator=function(){return this._events.getAllIterator()};Timeline.DefaultEventSource.prototype.getCount=function(){return this._events.getCount()};Timeline.DefaultEventSource.prototype.getEarliestDate=function(){return this._events.getEarliestDate()};Timeline.DefaultEventSource.prototype.getLatestDate=function(){return this._events.getLatestDate()};
Timeline.DefaultEventSource.prototype._fire=function(a,b){for(var f=0;f<this._listeners.length;f++){var e=this._listeners[f];if(a in e)try{e[a].apply(e,b)}catch(g){SimileAjax.Debug.exception(g)}}};Timeline.DefaultEventSource.prototype._getBaseURL=function(a){if(a.indexOf("://")<0)var b=this._getBaseURL(document.location.href),a=a.substr(0,1)=="/"?b.substr(0,b.indexOf("/",b.indexOf("://")+3))+a:b+a;b=a.lastIndexOf("/");return b<0?"":a.substr(0,b+1)};
Timeline.DefaultEventSource.prototype._resolveRelativeURL=function(a,b){return a==null||a==""?a:a.indexOf("://")>0?a:a.substr(0,1)=="/"?b.substr(0,b.indexOf("/",b.indexOf("://")+3))+a:b+a};
Timeline.DefaultEventSource.Event=function(a){function b(b){return a[b]!=null&&a[b]!=""?a[b]:null}var f=a.id?a.id.trim():"";this._id=f.length>0?f:Timeline.EventUtils.getNewEventID();this._instant=a.instant||a.end==null;this._start=a.start;this._end=a.end!=null?a.end:a.start;this._latestStart=a.latestStart!=null?a.latestStart:a.instant?this._end:this._start;this._earliestEnd=a.earliestEnd!=null?a.earliestEnd:this._end;f=[];if(this._start>this._latestStart)this._latestStart=this._start,f.push("start is > latestStart");
if(this._start>this._earliestEnd)this._earliestEnd=this._latestStart,f.push("start is > earliestEnd");if(this._start>this._end)this._end=this._earliestEnd,f.push("start is > end");if(this._latestStart>this._earliestEnd)this._earliestEnd=this._latestStart,f.push("latestStart is > earliestEnd");if(this._latestStart>this._end)this._end=this._earliestEnd,f.push("latestStart is > end");if(this._earliestEnd>this._end)this._end=this._earliestEnd,f.push("earliestEnd is > end");this._eventID=b("eventID");
this._text=a.text!=null?SimileAjax.HTML.deEntify(a.text):"";f.length>0&&(this._text+=" PROBLEM: "+f.join(", "));this._description=SimileAjax.HTML.deEntify(a.description);this._image=b("image");this._link=b("link");this._title=b("hoverText");this._title=b("caption");this._icon=b("icon");this._color=b("color");this._textColor=b("textColor");this._classname=b("classname");this._tapeImage=b("tapeImage");this._tapeRepeat=b("tapeRepeat");this._trackNum=b("trackNum");if(this._trackNum!=null)this._trackNum=
parseInt(this._trackNum);this._wikiSection=this._wikiURL=null};
Timeline.DefaultEventSource.Event.prototype={getID:function(){return this._id},isInstant:function(){return this._instant},isImprecise:function(){return this._start!=this._latestStart||this._end!=this._earliestEnd},getStart:function(){return this._start},getEnd:function(){return this._end},getLatestStart:function(){return this._latestStart},getEarliestEnd:function(){return this._earliestEnd},getEventID:function(){return this._eventID},getText:function(){return this._text},getDescription:function(){return this._description},
getImage:function(){return this._image},getLink:function(){return this._link},getIcon:function(){return this._icon},getColor:function(){return this._color},getTextColor:function(){return this._textColor},getClassName:function(){return this._classname},getTapeImage:function(){return this._tapeImage},getTapeRepeat:function(){return this._tapeRepeat},getTrackNum:function(){return this._trackNum},getProperty:function(){return null},getWikiURL:function(){return this._wikiURL},getWikiSection:function(){return this._wikiSection},
setWikiInfo:function(a,b){this._wikiURL=a;this._wikiSection=b},fillDescription:function(a){a.innerHTML=this._description},fillWikiInfo:function(a){a.style.display="none";if(!(this._wikiURL==null||this._wikiSection==null)){var b=this.getProperty("wikiID");if(b==null||b.length==0)b=this.getText();if(!(b==null||b.length==0)){a.style.display="inline";var b=b.replace(/\s/g,"_"),b=this._wikiURL+this._wikiSection.replace(/\s/g,"_")+"/"+b,f=document.createElement("a");f.href=b;f.target="new";f.innerHTML=
Timeline.strings[Timeline.clientLocale].wikiLinkLabel;a.appendChild(document.createTextNode("["));a.appendChild(f);a.appendChild(document.createTextNode("]"))}}},fillTime:function(a,b){this._instant?this.isImprecise()?(a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._start))),a.appendChild(a.ownerDocument.createElement("br")),a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._end)))):a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._start))):this.isImprecise()?
(a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._start)+" ~ "+b.labelPrecise(this._latestStart))),a.appendChild(a.ownerDocument.createElement("br")),a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._earliestEnd)+" ~ "+b.labelPrecise(this._end)))):(a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._start))),a.appendChild(a.ownerDocument.createElement("br")),a.appendChild(a.ownerDocument.createTextNode(b.labelPrecise(this._end))))},fillInfoBubble:function(a,
b,f){var e=a.ownerDocument,g=this.getText(),i=this.getLink(),d=this.getImage();if(d!=null){var c=e.createElement("img");c.src=d;b.event.bubble.imageStyler(c);a.appendChild(c)}d=e.createElement("div");g=e.createTextNode(g);i!=null?(c=e.createElement("a"),c.href=i,c.appendChild(g),d.appendChild(c)):d.appendChild(g);b.event.bubble.titleStyler(d);a.appendChild(d);i=e.createElement("div");this.fillDescription(i);b.event.bubble.bodyStyler(i);a.appendChild(i);i=e.createElement("div");this.fillTime(i,f);
b.event.bubble.timeStyler(i);a.appendChild(i);f=e.createElement("div");this.fillWikiInfo(f);b.event.bubble.wikiStyler(f);a.appendChild(f)}};
