Timeline.version="2.3.0";Timeline.ajax_lib_version=SimileAjax.version;Timeline.display_version=Timeline.version+" (with Ajax lib "+Timeline.ajax_lib_version+")";Timeline.strings={};Timeline.HORIZONTAL=0;Timeline.VERTICAL=1;Timeline._defaultTheme=null;Timeline.getDefaultLocale=function(){return Timeline.clientLocale};
Timeline.create=function(a,d,b,e){if(Timeline.timelines==null)Timeline.timelines=[];var f=Timeline.timelines.length;Timeline.timelines[f]=null;a=new Timeline._Impl(a,d,b,e,f);return Timeline.timelines[f]=a};
Timeline.createBandInfo=function(a){var d="theme"in a?a.theme:Timeline.getDefaultTheme(),b="eventSource"in a?a.eventSource:null,e=new Timeline.LinearEther({centersOn:"date"in a?a.date:new Date,interval:SimileAjax.DateTime.gregorianUnitLengths[a.intervalUnit],pixelsPerInterval:a.intervalPixels,theme:d}),f=new Timeline.GregorianEtherPainter({unit:a.intervalUnit,multiple:"multiple"in a?a.multiple:1,theme:d,align:"align"in a?a.align:void 0}),c={showText:"showEventText"in a?a.showEventText:!0,theme:d};
if("eventPainterParams"in a)for(var g in a.eventPainterParams)c[g]=a.eventPainterParams[g];if("trackHeight"in a)c.trackHeight=a.trackHeight;if("trackGap"in a)c.trackGap=a.trackGap;g="overview"in a&&a.overview?"overview":"layout"in a?a.layout:"original";if("eventPainter"in a)c=new a.eventPainter(c);else switch(g){case "overview":c=new Timeline.OverviewEventPainter(c);break;case "detailed":c=new Timeline.DetailedEventPainter(c);break;default:c=new Timeline.OriginalEventPainter(c)}return{width:a.width,
eventSource:b,timeZone:"timeZone"in a?a.timeZone:0,ether:e,etherPainter:f,eventPainter:c,theme:d,zoomIndex:"zoomIndex"in a?a.zoomIndex:0,zoomSteps:"zoomSteps"in a?a.zoomSteps:null}};
Timeline.createHotZoneBandInfo=function(a){var d="theme"in a?a.theme:Timeline.getDefaultTheme(),b="eventSource"in a?a.eventSource:null,e=new Timeline.HotZoneEther({centersOn:"date"in a?a.date:new Date,interval:SimileAjax.DateTime.gregorianUnitLengths[a.intervalUnit],pixelsPerInterval:a.intervalPixels,zones:a.zones,theme:d}),f=new Timeline.HotZoneGregorianEtherPainter({unit:a.intervalUnit,zones:a.zones,theme:d,align:"align"in a?a.align:void 0}),c={showText:"showEventText"in a?a.showEventText:!0,theme:d};
if("eventPainterParams"in a)for(var g in a.eventPainterParams)c[g]=a.eventPainterParams[g];if("trackHeight"in a)c.trackHeight=a.trackHeight;if("trackGap"in a)c.trackGap=a.trackGap;g="overview"in a&&a.overview?"overview":"layout"in a?a.layout:"original";if("eventPainter"in a)c=new a.eventPainter(c);else switch(g){case "overview":c=new Timeline.OverviewEventPainter(c);break;case "detailed":c=new Timeline.DetailedEventPainter(c);break;default:c=new Timeline.OriginalEventPainter(c)}return{width:a.width,
eventSource:b,timeZone:"timeZone"in a?a.timeZone:0,ether:e,etherPainter:f,eventPainter:c,theme:d,zoomIndex:"zoomIndex"in a?a.zoomIndex:0,zoomSteps:"zoomSteps"in a?a.zoomSteps:null}};Timeline.getDefaultTheme=function(){if(Timeline._defaultTheme==null)Timeline._defaultTheme=Timeline.ClassicTheme.create(Timeline.getDefaultLocale());return Timeline._defaultTheme};Timeline.setDefaultTheme=function(a){Timeline._defaultTheme=a};
Timeline.loadXML=function(a,d){SimileAjax.XmlHttp.get(a,function(b){alert("Failed to load data xml from "+a+"\n"+b)},function(b){var e=b.responseXML;!e.documentElement&&b.responseStream&&e.load(b.responseStream);d(e,a)})};Timeline.loadJSON=function(a,d){SimileAjax.XmlHttp.get(a,function(b){alert("Failed to load json data from "+a+"\n"+b)},function(b){d(eval("("+b.responseText+")"),a)})};Timeline.getTimelineFromID=function(a){return Timeline.timelines[a]};
Timeline.writeVersion=function(a){document.getElementById(a).innerHTML=this.display_version};
Timeline._Impl=function(a,d,b,e,f){SimileAjax.WindowManager.initialize();this._containerDiv=a;this._bandInfos=d;this._orientation=b==null?Timeline.HORIZONTAL:b;this._unit=e!=null?e:SimileAjax.NativeDateUnit;this._starting=!0;this._autoResizing=!1;this.autoWidth=d&&d[0]&&d[0].theme&&d[0].theme.autoWidth;this.autoWidthAnimationTime=d&&d[0]&&d[0].theme&&d[0].theme.autoWidthAnimationTime;this.timelineID=f;this.timeline_start=d&&d[0]&&d[0].theme&&d[0].theme.timeline_start;this.timeline_stop=d&&d[0]&&d[0].theme&&
d[0].theme.timeline_stop;this.timeline_at_stop=this.timeline_at_start=!1;this._initialize()};Timeline._Impl.prototype.dispose=function(){for(var a=0;a<this._bands.length;a++)this._bands[a].dispose();this._bandInfos=this._bands=null;this._containerDiv.innerHTML="";Timeline.timelines[this.timelineID]=null};Timeline._Impl.prototype.getBandCount=function(){return this._bands.length};Timeline._Impl.prototype.getBand=function(a){return this._bands[a]};
Timeline._Impl.prototype.finishedEventLoading=function(){this._autoWidthCheck(!0);this._starting=!1};Timeline._Impl.prototype.layout=function(){this._autoWidthCheck(!0);this._distributeWidths()};Timeline._Impl.prototype.paint=function(){for(var a=0;a<this._bands.length;a++)this._bands[a].paint()};Timeline._Impl.prototype.getDocument=function(){return this._containerDiv.ownerDocument};Timeline._Impl.prototype.addDiv=function(a){this._containerDiv.appendChild(a)};
Timeline._Impl.prototype.removeDiv=function(a){this._containerDiv.removeChild(a)};Timeline._Impl.prototype.isHorizontal=function(){return this._orientation==Timeline.HORIZONTAL};Timeline._Impl.prototype.isVertical=function(){return this._orientation==Timeline.VERTICAL};Timeline._Impl.prototype.getPixelLength=function(){return this._orientation==Timeline.HORIZONTAL?this._containerDiv.offsetWidth:this._containerDiv.offsetHeight};
Timeline._Impl.prototype.getPixelWidth=function(){return this._orientation==Timeline.VERTICAL?this._containerDiv.offsetWidth:this._containerDiv.offsetHeight};Timeline._Impl.prototype.getUnit=function(){return this._unit};Timeline._Impl.prototype.getWidthStyle=function(){return this._orientation==Timeline.HORIZONTAL?"height":"width"};
Timeline._Impl.prototype.loadXML=function(a,d){var b=this,e=function(c){alert("Failed to load data xml from "+a+"\n"+c);b.hideLoadingMessage()},f=function(c){try{var e=c.responseXML;!e.documentElement&&c.responseStream&&e.load(c.responseStream);d(e,a)}finally{b.hideLoadingMessage()}};this.showLoadingMessage();window.setTimeout(function(){SimileAjax.XmlHttp.get(a,e,f)},0)};
Timeline._Impl.prototype.loadJSON=function(a,d){var b=this,e=function(c){alert("Failed to load json data from "+a+"\n"+c);b.hideLoadingMessage()},f=function(c){try{d(eval("("+c.responseText+")"),a)}finally{b.hideLoadingMessage()}};this.showLoadingMessage();window.setTimeout(function(){SimileAjax.XmlHttp.get(a,e,f)},0)};Timeline._Impl.prototype._autoWidthScrollListener=function(a){a.getTimeline()._autoWidthCheck(!1)};
Timeline._Impl.prototype._autoWidthCheck=function(a){function d(){var a=b.getWidthStyle();if(e)b._containerDiv.style[a]=f+"px";else{b._autoResizing=!0;var d={};d[a]=f+"px";SimileAjax.jQuery(b._containerDiv).animate(d,b.autoWidthAnimationTime,"linear",function(){b._autoResizing=!1})}}var b=this,e=b._starting,f=0;b.autoWidth&&function(){var c=0,e=b.getPixelWidth();if(!b._autoResizing){for(var h=0;h<b._bands.length;h++)b._bands[h].checkAutoWidth(),c+=b._bandInfos[h].width;if(c>e||a)f=c,d(),b._distributeWidths()}}()};
Timeline._Impl.prototype._initialize=function(){var a=this._containerDiv,d=a.ownerDocument;a.className=a.className.split(" ").concat("timeline-container").join(" ");var b=this.isHorizontal()?"horizontal":"vertical";for(a.className+=" timeline-"+b;a.firstChild;)a.removeChild(a.firstChild);b=SimileAjax.Graphics.createTranslucentImage(Timeline.urlPrefix+(this.isHorizontal()?"images/copyright-vertical.png":"images/copyright.png"));b.className="timeline-copyright";b.title="Timeline copyright SIMILE - www.code.google.com/p/simile-widgets/";
SimileAjax.DOM.registerEvent(b,"click",function(){window.location="http://code.google.com/p/simile-widgets/"});a.appendChild(b);this._bands=[];for(b=0;b<this._bandInfos.length;b++)this._bands.push(new Timeline._Band(this,this._bandInfos[b],b));this._distributeWidths();for(b=0;b<this._bandInfos.length;b++){var e=this._bandInfos[b];"syncWith"in e&&this._bands[b].setSyncWithBand(this._bands[e.syncWith],"highlight"in e?e.highlight:!1)}if(this.autoWidth)for(b=0;b<this._bands.length;b++)this._bands[b].addOnScrollListener(this._autoWidthScrollListener);
var f=SimileAjax.Graphics.createMessageBubble(d);f.containerDiv.className="timeline-message-container";a.appendChild(f.containerDiv);f.contentDiv.className="timeline-message";f.contentDiv.innerHTML="<img src='"+Timeline.urlPrefix+"images/progress-running.gif' /> Loading...";this.showLoadingMessage=function(){f.containerDiv.style.display="block"};this.hideLoadingMessage=function(){f.containerDiv.style.display="none"}};
Timeline._Impl.prototype._distributeWidths=function(){for(var a=this.getPixelLength(),d=this.getPixelWidth(),b=0,e=0;e<this._bands.length;e++){var f=this._bands[e],c=this._bandInfos[e].width;if(typeof c=="string"){var g=c.indexOf("%");g>0?(c=parseInt(c.substr(0,g)),c=Math.round(c*d/100)):c=parseInt(c)}f.setBandShiftAndWidth(b,c);f.setViewLength(a);b+=c}};
Timeline._Impl.prototype.shiftOK=function(a,d){var b=d>0,e=d<0;if(b&&this.timeline_start==null||e&&this.timeline_stop==null||d==0)return!0;for(var f=!1,c=0;c<this._bands.length&&!f;c++)f=this._bands[c].busy();if(f)return!0;if(b&&this.timeline_at_start||e&&this.timeline_at_stop)return!1;e=!1;for(c=0;c<this._bands.length&&!e;c++)e=this._bands[c],e=b?(c==a?e.getMinVisibleDateAfterDelta(d):e.getMinVisibleDate())>=this.timeline_start:(c==a?e.getMaxVisibleDateAfterDelta(d):e.getMaxVisibleDate())<=this.timeline_stop;
b?(this.timeline_at_start=!e,this.timeline_at_stop=!1):(this.timeline_at_stop=!e,this.timeline_at_start=!1);return e};Timeline._Impl.prototype.zoom=function(a,d,b,e){var f=null,c=/^timeline-band-([0-9]+)$/.exec(e.id);c&&(f=parseInt(c[1]));f!=null&&this._bands[f].zoom(a,d,b,e);this.paint()};
