<ul class="nav nav-pills">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
            <li <?php if($page->isActive()) echo 'class="active"'?> role="presentation">
                <a class="" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php $count++ ?>
    <?php endforeach; ?>
</ul>
